In [ ]:
import wandb
wandb.login() # This will prompt you to paste your free W&B API key

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: (1) Create a W&B account
wandb: (2) Use an existing W&B account
wandb: (3) Don't visualize my results

wandb: Enter your choice: 2

wandb: You chose 'Use an existing W&B account'
wandb: Logging into https://api.wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: Create a new API key at: https://wandb.ai/authorize?ref=models
wandb: Store your API key securely and do not share it.

wandb: Paste your API key and hit enter: ··········

wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: marvin-cy-wong (marvin-cy-wong-ucla) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [ ]:
!pip install -U "transformers>=4.48.0" datasets accelerate scikit-learn pandas

Requirement already satisfied: transformers>=4.48.0 in /usr/local/lib/python3.12/dist-packages (5.13.1)
Collecting transformers>=4.48.0
  Downloading transformers-5.14.1-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Collecting datasets
  Downloading datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Collecting scikit-learn
  Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting pandas
  Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.5/79.5 kB 9.9 MB/s eta 0:00:00
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (1.23.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers>=4.48.0) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.7)
Collecting pyarrow>=21.0.0 (from datasets)
  Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.1)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2026.4.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.11.0+cu128)
Requirement already satisfied: scipy>=1.10.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (3.14.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.48.0) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.48.0) (1.5.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.48.0) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.9)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.48.0) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.48.0) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers>=4.48.0) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (1.24.2)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=2.0.0->accelerate) (1.5.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.48.0) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers>=4.48.0) (2.20.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.48.0) (0.1.2)
Downloading transformers-5.14.1-py3-none-any.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 147.8 MB/s eta 0:00:00
Downloading datasets-5.0.0-py3-none-any.whl (555 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 41.8 MB/s eta 0:00:00
Downloading scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 120.2 MB/s eta 0:00:00
Downloading pandas-3.0.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (11.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.0/11.0 MB 118.1 MB/s eta 0:00:00
Downloading pyarrow-25.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (50.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 48.9 MB/s eta 0:00:00
Installing collected packages: pyarrow, scikit-learn, pandas, datasets, transformers
  Attempting uninstall: pyarrow
    Found existing installation: pyarrow 18.1.0
    Uninstalling pyarrow-18.1.0:
      Successfully uninstalled pyarrow-18.1.0
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
  Attempting uninstall: pandas
    Found existing installation: pandas 2.2.2
    Uninstalling pandas-2.2.2:
      Successfully uninstalled pandas-2.2.2
  Attempting uninstall: datasets
    Found existing installation: datasets 4.0.0
    Uninstalling datasets-4.0.0:
      Successfully uninstalled datasets-4.0.0
  Attempting uninstall: transformers
    Found existing installation: transformers 5.13.1
    Uninstalling transformers-5.13.1:
      Successfully uninstalled transformers-5.13.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires pandas==2.2.2, but you have pandas 3.0.5 which is incompatible.
cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
dask-cudf-cu12 26.2.1 requires pandas<2.4.0,>=2.0, but you have pandas 3.0.5 which is incompatible.
Successfully installed datasets-5.0.0 pandas-3.0.5 pyarrow-25.0.0 scikit-learn-1.9.0 transformers-5.14.1

In [ ]:
# 1. Move back to the base content directory
%cd /content

# 2. Delete the old repository completely
!rm -rf r-AITA_classifier

# 3. Clone it fresh
!git clone https://github.com/marvinwong12/r-AITA_classifier.git

# 4. Move back into the fresh folder
%cd r-AITA_classifier

/content
Cloning into 'r-AITA_classifier'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 66 (delta 34), reused 48 (delta 19), pack-reused 0 (from 0)
Receiving objects: 100% (66/66), 597.73 KiB | 2.27 MiB/s, done.
Resolving deltas: 100% (34/34), done.
/content/r-AITA_classifier

In [ ]:
import os
from google.colab import files

# Create the expected folder structure
os.makedirs("data/raw", exist_ok=True)

# Upload your CSV
uploaded = files.upload()

# Move the uploaded file to data/raw/
for filename in uploaded.keys():
    os.rename(filename, f"data/raw/{filename}")

Saving aita_full.csv to aita_full.csv

In [ ]:
!python src/train_modernbert.py \
    --data_path "data/raw/aita_10k_sample.csv" \
    --output_dir "models/modernbert_aita_10k" \
    --batch_size 4 \
    --grad_accum 4 \
    --max_length 1024 \
    --lr 1.5e-5 \
    --fp16

=== Fine-Tuning answerdotai/ModernBERT-large ===
Applying strict 1:1 undersampling...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
config.json: 100% 1.19k/1.19k [00:00<00:00, 3.59MB/s]
tokenizer_config.json: 100% 20.8k/20.8k [00:00<00:00, 59.2MB/s]
tokenizer.json: 100% 2.13M/2.13M [00:00<00:00, 119MB/s]
special_tokens_map.json: 100% 694/694 [00:00<00:00, 3.43MB/s]

model.safetensors: downloading bytes:  18% 279M/1.58G [00:02<00:04, 271MB/s, 23.0MB/s  ]
model.safetensors: downloading bytes:  37% 592M/1.58G [00:02<00:01, 523MB/s, 46.9MB/s  ]
model.safetensors: downloading bytes:  89% 1.42G/1.58G [00:04<00:00, 677MB/s,  113MB/s  ]
model.safetensors: downloading bytes:  94% 1.49G/1.58G [00:04<00:00, 481MB/s,  122MB/s  ]
model.safetensors: reconstructing file:  65% 1.02G/1.58G [00:04<00:02, 269MB/s, 80.8MB/s  ]
model.safetensors: downloading bytes: 100% 1.50G/1.50G [00:05<00:00, 272MB/s,  121MB/s  ]
model.safetensors: reconstructing file: 100% 1.58G/1.58G [00:05<00:00, 288MB/s,  131MB/s  ]
Loading weights: 100% 172/172 [00:00<00:00, 4664.56it/s]
[transformers] ModernBertForSequenceClassification LOAD REPORT from: answerdotai/ModernBERT-large
Key               | Status     |
------------------+------------+-
decoder.bias      | UNEXPECTED |
classifier.weight | MISSING    |
classifier.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100% 4148/4148 [00:01<00:00, 3089.85 examples/s]
Map: 100% 2000/2000 [00:00<00:00, 2914.65 examples/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting Fine-Tuning Process...
[transformers] The tokenizer has new PAD/BOS/EOS tokens that differ from the model config and generation config. The model config and generation config were aligned accordingly, being updated with the tokenizer's values. Updated tokens: {'eos_token_id': None, 'bos_token_id': None}.
{'loss': '2.91', 'grad_norm': '68.63', 'learning_rate': '1.846e-06', 'epoch': '0.09643'}
{'loss': '2.861', 'grad_norm': '60.19', 'learning_rate': '3.769e-06', 'epoch': '0.1929'}
{'loss': '2.9', 'grad_norm': '56.24', 'learning_rate': '5.692e-06', 'epoch': '0.2893'}
{'loss': '2.885', 'grad_norm': '62.33', 'learning_rate': '7.615e-06', 'epoch': '0.3857'}
{'loss': '2.886', 'grad_norm': '25.58', 'learning_rate': '9.538e-06', 'epoch': '0.4822'}
{'loss': '2.812', 'grad_norm': '34.24', 'learning_rate': '1.146e-05', 'epoch': '0.5786'}
{'loss': '2.884', 'grad_norm': '22.91', 'learning_rate': '1.338e-05', 'epoch': '0.675'}
{'loss': '2.772', 'grad_norm': '33.39', 'learning_rate': '1.495e-05', 'epoch': '0.7715'}
{'loss': '2.777', 'grad_norm': '33.47', 'learning_rate': '1.461e-05', 'epoch': '0.8679'}
{'loss': '2.876', 'grad_norm': '29.23', 'learning_rate': '1.427e-05', 'epoch': '0.9643'}
 20% 260/1300 [04:40<15:16,  1.13it/s]
  0% 0/500 [00:00<?, ?it/s]
  0% 2/500 [00:00<00:25, 19.28it/s]
  1% 4/500 [00:00<00:31, 15.61it/s]
  1% 6/500 [00:00<00:33, 14.79it/s]
  2% 8/500 [00:00<00:38, 12.88it/s]
  2% 10/500 [00:00<00:34, 14.14it/s]
  2% 12/500 [00:00<00:43, 11.34it/s]
  3% 14/500 [00:01<00:40, 11.94it/s]
  3% 16/500 [00:01<00:42, 11.49it/s]
  4% 18/500 [00:01<00:44, 10.76it/s]
  4% 20/500 [00:01<00:42, 11.26it/s]
  4% 22/500 [00:01<00:42, 11.34it/s]
  5% 24/500 [00:01<00:41, 11.48it/s]
  5% 26/500 [00:02<00:41, 11.38it/s]
  6% 28/500 [00:02<00:45, 10.30it/s]
  6% 30/500 [00:02<00:42, 10.99it/s]
  6% 32/500 [00:02<00:43, 10.84it/s]
  7% 34/500 [00:02<00:42, 11.09it/s]
  7% 36/500 [00:03<00:41, 11.31it/s]
  8% 38/500 [00:03<00:39, 11.70it/s]
  8% 40/500 [00:03<00:39, 11.79it/s]
  8% 42/500 [00:03<00:40, 11.31it/s]
  9% 44/500 [00:03<00:38, 11.82it/s]
  9% 46/500 [00:03<00:35, 12.86it/s]
 10% 48/500 [00:04<00:35, 12.89it/s]
 10% 50/500 [00:04<00:38, 11.70it/s]
 10% 52/500 [00:04<00:36, 12.18it/s]
 11% 54/500 [00:04<00:38, 11.51it/s]
 11% 56/500 [00:04<00:38, 11.50it/s]
 12% 58/500 [00:04<00:40, 10.86it/s]
 12% 60/500 [00:05<00:40, 10.97it/s]
 12% 62/500 [00:05<00:38, 11.31it/s]
 13% 64/500 [00:05<00:38, 11.43it/s]
 13% 66/500 [00:05<00:39, 11.04it/s]
 14% 68/500 [00:05<00:38, 11.30it/s]
 14% 70/500 [00:05<00:34, 12.49it/s]
 14% 72/500 [00:06<00:33, 12.82it/s]
 15% 74/500 [00:06<00:29, 14.22it/s]
 15% 76/500 [00:06<00:32, 13.15it/s]
 16% 78/500 [00:06<00:32, 13.17it/s]
 16% 80/500 [00:06<00:32, 13.10it/s]
 16% 82/500 [00:06<00:33, 12.55it/s]
 17% 84/500 [00:07<00:32, 12.99it/s]
 17% 86/500 [00:07<00:34, 11.88it/s]
 18% 88/500 [00:07<00:32, 12.63it/s]
 18% 90/500 [00:07<00:32, 12.57it/s]
 18% 92/500 [00:07<00:34, 11.74it/s]
 19% 94/500 [00:07<00:33, 11.98it/s]
 19% 96/500 [00:08<00:32, 12.25it/s]
 20% 98/500 [00:08<00:35, 11.43it/s]
 20% 100/500 [00:08<00:37, 10.71it/s]
 20% 102/500 [00:08<00:36, 10.94it/s]
 21% 104/500 [00:08<00:36, 10.73it/s]
 21% 106/500 [00:09<00:37, 10.53it/s]
 22% 108/500 [00:09<00:35, 10.91it/s]
 22% 110/500 [00:09<00:33, 11.70it/s]
 22% 112/500 [00:09<00:35, 10.98it/s]
 23% 114/500 [00:09<00:34, 11.26it/s]
 23% 116/500 [00:09<00:32, 11.78it/s]
 24% 118/500 [00:10<00:32, 11.83it/s]
 24% 120/500 [00:10<00:34, 11.06it/s]
 24% 122/500 [00:10<00:35, 10.53it/s]
 25% 124/500 [00:10<00:33, 11.20it/s]
 25% 126/500 [00:10<00:31, 12.00it/s]
 26% 128/500 [00:10<00:28, 13.18it/s]
 26% 130/500 [00:11<00:30, 12.06it/s]
 26% 132/500 [00:11<00:35, 10.31it/s]
 27% 134/500 [00:11<00:35, 10.34it/s]
 27% 136/500 [00:11<00:32, 11.33it/s]
 28% 138/500 [00:11<00:29, 12.33it/s]
 28% 140/500 [00:11<00:30, 11.93it/s]
 28% 142/500 [00:12<00:33, 10.83it/s]
 29% 144/500 [00:12<00:33, 10.57it/s]
 29% 146/500 [00:12<00:31, 11.07it/s]
 30% 148/500 [00:12<00:30, 11.58it/s]
 30% 150/500 [00:12<00:29, 11.99it/s]
 30% 152/500 [00:12<00:28, 12.16it/s]
 31% 154/500 [00:13<00:29, 11.67it/s]
 31% 156/500 [00:13<00:29, 11.82it/s]
 32% 158/500 [00:13<00:28, 11.88it/s]
 32% 160/500 [00:13<00:29, 11.67it/s]
 32% 162/500 [00:13<00:29, 11.37it/s]
 33% 165/500 [00:14<00:25, 13.21it/s]
 33% 167/500 [00:14<00:27, 12.13it/s]
 34% 169/500 [00:14<00:27, 11.89it/s]
 34% 171/500 [00:14<00:28, 11.62it/s]
 35% 173/500 [00:14<00:29, 11.05it/s]
 35% 175/500 [00:14<00:28, 11.42it/s]
 35% 177/500 [00:15<00:27, 11.64it/s]
 36% 179/500 [00:15<00:26, 12.22it/s]
 36% 181/500 [00:15<00:25, 12.42it/s]
 37% 183/500 [00:15<00:30, 10.47it/s]
 37% 185/500 [00:15<00:28, 11.03it/s]
 37% 187/500 [00:15<00:25, 12.04it/s]
 38% 189/500 [00:16<00:28, 10.90it/s]
 38% 191/500 [00:16<00:27, 11.27it/s]
 39% 193/500 [00:16<00:26, 11.74it/s]
 39% 195/500 [00:16<00:23, 12.80it/s]
 39% 197/500 [00:16<00:23, 12.92it/s]
 40% 199/500 [00:17<00:25, 11.75it/s]
 40% 201/500 [00:17<00:23, 12.89it/s]
 41% 203/500 [00:17<00:24, 12.12it/s]
 41% 205/500 [00:17<00:23, 12.40it/s]
 41% 207/500 [00:17<00:26, 11.13it/s]
 42% 209/500 [00:17<00:24, 11.71it/s]
 42% 211/500 [00:18<00:24, 11.73it/s]
 43% 213/500 [00:18<00:24, 11.52it/s]
 43% 215/500 [00:18<00:25, 11.13it/s]
 43% 217/500 [00:18<00:24, 11.76it/s]
 44% 219/500 [00:18<00:23, 12.05it/s]
 44% 221/500 [00:18<00:22, 12.25it/s]
 45% 223/500 [00:19<00:23, 11.59it/s]
 45% 225/500 [00:19<00:24, 11.03it/s]
 45% 227/500 [00:19<00:22, 12.11it/s]
 46% 229/500 [00:19<00:21, 12.53it/s]
 46% 231/500 [00:19<00:25, 10.52it/s]
 47% 233/500 [00:19<00:22, 12.06it/s]
 47% 235/500 [00:20<00:22, 11.88it/s]
 47% 237/500 [00:20<00:22, 11.46it/s]
 48% 239/500 [00:20<00:21, 12.06it/s]
 48% 241/500 [00:20<00:20, 12.41it/s]
 49% 243/500 [00:20<00:21, 12.19it/s]
 49% 245/500 [00:20<00:21, 11.92it/s]
 49% 247/500 [00:21<00:21, 11.72it/s]
 50% 249/500 [00:21<00:23, 10.84it/s]
 50% 251/500 [00:21<00:23, 10.74it/s]
 51% 253/500 [00:21<00:21, 11.57it/s]
 51% 255/500 [00:21<00:23, 10.35it/s]
 51% 257/500 [00:22<00:23, 10.55it/s]
 52% 259/500 [00:22<00:22, 10.78it/s]
 52% 261/500 [00:22<00:23, 10.38it/s]
 53% 263/500 [00:22<00:21, 11.17it/s]
 53% 265/500 [00:22<00:22, 10.65it/s]
 53% 267/500 [00:22<00:22, 10.57it/s]
 54% 269/500 [00:23<00:20, 11.39it/s]
 54% 271/500 [00:23<00:20, 11.34it/s]
 55% 273/500 [00:23<00:19, 11.63it/s]
 55% 275/500 [00:23<00:19, 11.66it/s]
 55% 277/500 [00:23<00:19, 11.33it/s]
 56% 279/500 [00:23<00:18, 11.63it/s]
 56% 281/500 [00:24<00:19, 11.05it/s]
 57% 283/500 [00:24<00:21, 10.32it/s]
 57% 285/500 [00:24<00:21,  9.91it/s]
 57% 287/500 [00:24<00:20, 10.55it/s]
 58% 289/500 [00:24<00:19, 10.67it/s]
 58% 291/500 [00:25<00:18, 11.50it/s]
 59% 293/500 [00:25<00:18, 10.91it/s]
 59% 295/500 [00:25<00:16, 12.34it/s]
 59% 297/500 [00:25<00:17, 11.62it/s]
 60% 299/500 [00:25<00:16, 11.98it/s]
 60% 301/500 [00:25<00:18, 11.02it/s]
 61% 303/500 [00:26<00:16, 11.79it/s]
 61% 305/500 [00:26<00:16, 11.86it/s]
 61% 307/500 [00:26<00:17, 11.25it/s]
 62% 309/500 [00:26<00:16, 11.41it/s]
 62% 311/500 [00:26<00:16, 11.23it/s]
 63% 313/500 [00:27<00:17, 10.70it/s]
 63% 315/500 [00:27<00:15, 12.09it/s]
 63% 317/500 [00:27<00:14, 12.44it/s]
 64% 319/500 [00:27<00:16, 10.68it/s]
 64% 321/500 [00:27<00:15, 11.88it/s]
 65% 323/500 [00:27<00:15, 11.11it/s]
 65% 325/500 [00:28<00:14, 12.26it/s]
 65% 327/500 [00:28<00:15, 11.37it/s]
 66% 329/500 [00:28<00:14, 11.73it/s]
 66% 331/500 [00:28<00:13, 12.26it/s]
 67% 333/500 [00:28<00:13, 12.24it/s]
 67% 335/500 [00:28<00:13, 12.52it/s]
 67% 337/500 [00:29<00:13, 11.74it/s]
 68% 339/500 [00:29<00:14, 11.01it/s]
 68% 341/500 [00:29<00:13, 11.76it/s]
 69% 343/500 [00:29<00:12, 12.36it/s]
 69% 345/500 [00:29<00:13, 11.36it/s]
 69% 347/500 [00:29<00:14, 10.66it/s]
 70% 349/500 [00:30<00:13, 11.29it/s]
 70% 351/500 [00:30<00:14, 10.44it/s]
 71% 353/500 [00:30<00:13, 10.76it/s]
 71% 355/500 [00:30<00:13, 10.40it/s]
 71% 357/500 [00:30<00:14,  9.87it/s]
 72% 359/500 [00:31<00:13, 10.21it/s]
 72% 361/500 [00:31<00:12, 11.08it/s]
 73% 363/500 [00:31<00:13, 10.41it/s]
 73% 365/500 [00:31<00:12, 11.12it/s]
 73% 367/500 [00:31<00:12, 10.83it/s]
 74% 369/500 [00:32<00:13,  9.91it/s]
 74% 371/500 [00:32<00:12, 10.53it/s]
 75% 373/500 [00:32<00:11, 10.88it/s]
 75% 375/500 [00:32<00:10, 12.07it/s]
 75% 377/500 [00:32<00:10, 11.90it/s]
 76% 379/500 [00:32<00:10, 11.82it/s]
 76% 381/500 [00:33<00:10, 10.85it/s]
 77% 383/500 [00:33<00:10, 11.36it/s]
 77% 385/500 [00:33<00:09, 11.68it/s]
 77% 387/500 [00:33<00:09, 11.38it/s]
 78% 389/500 [00:33<00:09, 11.57it/s]
 78% 391/500 [00:33<00:09, 11.48it/s]
 79% 393/500 [00:34<00:09, 11.02it/s]
 79% 395/500 [00:34<00:08, 12.02it/s]
 79% 397/500 [00:34<00:08, 11.96it/s]
 80% 399/500 [00:34<00:08, 11.90it/s]
 80% 401/500 [00:34<00:07, 12.63it/s]
 81% 403/500 [00:34<00:08, 12.04it/s]
 81% 405/500 [00:35<00:08, 11.54it/s]
 81% 407/500 [00:35<00:08, 11.19it/s]
 82% 409/500 [00:35<00:08, 10.95it/s]
 82% 411/500 [00:35<00:08, 10.92it/s]
 83% 413/500 [00:35<00:07, 10.90it/s]
 83% 415/500 [00:36<00:07, 10.84it/s]
 83% 417/500 [00:36<00:07, 10.59it/s]
 84% 419/500 [00:36<00:07, 10.81it/s]
 84% 421/500 [00:36<00:07, 10.77it/s]
 85% 423/500 [00:36<00:06, 11.51it/s]
 85% 425/500 [00:36<00:06, 11.45it/s]
 85% 427/500 [00:37<00:06, 11.62it/s]
 86% 429/500 [00:37<00:05, 11.85it/s]
 86% 431/500 [00:37<00:05, 11.99it/s]
 87% 433/500 [00:37<00:05, 11.81it/s]
 87% 435/500 [00:37<00:05, 11.33it/s]
 87% 437/500 [00:37<00:05, 11.70it/s]
 88% 439/500 [00:38<00:05, 11.79it/s]
 88% 441/500 [00:38<00:04, 11.85it/s]
 89% 443/500 [00:38<00:04, 12.71it/s]
 89% 445/500 [00:38<00:04, 11.78it/s]
 89% 447/500 [00:38<00:04, 11.10it/s]
 90% 449/500 [00:38<00:04, 11.43it/s]
 90% 451/500 [00:39<00:04, 12.11it/s]
 91% 453/500 [00:39<00:03, 12.62it/s]
 91% 455/500 [00:39<00:03, 12.29it/s]
 91% 457/500 [00:39<00:03, 11.86it/s]
 92% 459/500 [00:39<00:03, 11.21it/s]
 92% 461/500 [00:40<00:03, 10.64it/s]
 93% 463/500 [00:40<00:03, 10.66it/s]
 93% 465/500 [00:40<00:03, 11.35it/s]
 93% 467/500 [00:40<00:02, 11.16it/s]
 94% 469/500 [00:40<00:02, 12.30it/s]
 94% 471/500 [00:40<00:02, 10.73it/s]
 95% 473/500 [00:41<00:02, 11.37it/s]
 95% 475/500 [00:41<00:02, 11.29it/s]
 95% 477/500 [00:41<00:01, 12.09it/s]
 96% 479/500 [00:41<00:01, 11.69it/s]
 96% 481/500 [00:41<00:01, 11.45it/s]
 97% 483/500 [00:41<00:01, 12.07it/s]
 97% 485/500 [00:42<00:01, 11.69it/s]
 97% 487/500 [00:42<00:01, 11.01it/s]
 98% 489/500 [00:42<00:00, 11.96it/s]
 98% 491/500 [00:42<00:00, 11.55it/s]
 99% 493/500 [00:42<00:00, 11.60it/s]
 99% 495/500 [00:42<00:00, 11.10it/s]
 99% 497/500 [00:43<00:00, 10.04it/s]
100% 499/500 [00:43<00:00,  9.89it/s]
{'eval_loss': '0.8566', 'eval_accuracy': '0.36', 'eval_f1_macro': '0.3547', 'eval_precision_macro': '0.5347', 'eval_recall_macro': '0.5253', 'eval_runtime': '43.74', 'eval_samples_per_second': '45.72', 'eval_steps_per_second': '11.43', 'epoch': '1'}

 20% 260/1300 [05:24<15:16,  1.13it/s]

Writing model shards:   0% 0/1 [00:00<?, ?it/s]
Writing model shards: 100% 1/1 [00:06<00:00,  6.36s/it]
{'loss': '2.642', 'grad_norm': '26.28', 'learning_rate': '1.393e-05', 'epoch': '1.058'}
{'loss': '2.557', 'grad_norm': '17.38', 'learning_rate': '1.359e-05', 'epoch': '1.154'}
{'loss': '2.751', 'grad_norm': '19.87', 'learning_rate': '1.325e-05', 'epoch': '1.251'}
{'loss': '2.588', 'grad_norm': '27.25', 'learning_rate': '1.291e-05', 'epoch': '1.347'}
{'loss': '2.723', 'grad_norm': '45.61', 'learning_rate': '1.257e-05', 'epoch': '1.444'}
{'loss': '2.61', 'grad_norm': '23.63', 'learning_rate': '1.223e-05', 'epoch': '1.54'}
{'loss': '2.496', 'grad_norm': '57.87', 'learning_rate': '1.189e-05', 'epoch': '1.636'}
{'loss': '2.539', 'grad_norm': '13.37', 'learning_rate': '1.155e-05', 'epoch': '1.733'}
{'loss': '2.731', 'grad_norm': '14.27', 'learning_rate': '1.121e-05', 'epoch': '1.829'}
{'loss': '2.473', 'grad_norm': '31.44', 'learning_rate': '1.087e-05', 'epoch': '1.926'}
 40% 520/1300 [10:20<11:41,  1.11it/s]
  0% 0/500 [00:00<?, ?it/s]
  0% 2/500 [00:00<00:25, 19.64it/s]
  1% 4/500 [00:00<00:30, 16.31it/s]
  1% 6/500 [00:00<00:32, 15.24it/s]
  2% 8/500 [00:00<00:38, 12.93it/s]
  2% 10/500 [00:00<00:34, 14.14it/s]
  2% 12/500 [00:00<00:43, 11.26it/s]
  3% 14/500 [00:01<00:41, 11.74it/s]
  3% 16/500 [00:01<00:42, 11.35it/s]
  4% 18/500 [00:01<00:45, 10.70it/s]
  4% 20/500 [00:01<00:43, 11.14it/s]
  4% 22/500 [00:01<00:42, 11.21it/s]
  5% 24/500 [00:02<00:42, 11.31it/s]
  5% 26/500 [00:02<00:42, 11.23it/s]
  6% 28/500 [00:02<00:46, 10.22it/s]
  6% 30/500 [00:02<00:42, 10.96it/s]
  6% 32/500 [00:02<00:43, 10.87it/s]
  7% 34/500 [00:02<00:41, 11.11it/s]
  7% 36/500 [00:03<00:41, 11.29it/s]
  8% 38/500 [00:03<00:39, 11.66it/s]
  8% 40/500 [00:03<00:39, 11.77it/s]
  8% 42/500 [00:03<00:40, 11.34it/s]
  9% 44/500 [00:03<00:38, 11.81it/s]
  9% 46/500 [00:03<00:35, 12.83it/s]
 10% 48/500 [00:04<00:35, 12.81it/s]
 10% 50/500 [00:04<00:38, 11.68it/s]
 10% 52/500 [00:04<00:36, 12.15it/s]
 11% 54/500 [00:04<00:38, 11.53it/s]
 11% 56/500 [00:04<00:38, 11.52it/s]
 12% 58/500 [00:04<00:40, 10.99it/s]
 12% 60/500 [00:05<00:39, 11.04it/s]
 12% 62/500 [00:05<00:38, 11.27it/s]
 13% 64/500 [00:05<00:37, 11.52it/s]
 13% 66/500 [00:05<00:39, 11.01it/s]
 14% 68/500 [00:05<00:38, 11.24it/s]
 14% 70/500 [00:05<00:34, 12.44it/s]
 14% 72/500 [00:06<00:33, 12.80it/s]
 15% 74/500 [00:06<00:29, 14.33it/s]
 15% 76/500 [00:06<00:32, 13.24it/s]
 16% 78/500 [00:06<00:31, 13.28it/s]
 16% 80/500 [00:06<00:32, 13.07it/s]
 16% 82/500 [00:06<00:33, 12.44it/s]
 17% 84/500 [00:07<00:32, 12.88it/s]
 17% 86/500 [00:07<00:35, 11.77it/s]
 18% 88/500 [00:07<00:32, 12.52it/s]
 18% 90/500 [00:07<00:32, 12.58it/s]
 18% 92/500 [00:07<00:34, 11.79it/s]
 19% 94/500 [00:07<00:33, 12.00it/s]
 19% 96/500 [00:08<00:33, 12.24it/s]
 20% 98/500 [00:08<00:35, 11.35it/s]
 20% 100/500 [00:08<00:37, 10.61it/s]
 20% 102/500 [00:08<00:36, 10.78it/s]
 21% 104/500 [00:08<00:36, 10.71it/s]
 21% 106/500 [00:09<00:37, 10.48it/s]
 22% 108/500 [00:09<00:36, 10.83it/s]
 22% 110/500 [00:09<00:33, 11.68it/s]
 22% 112/500 [00:09<00:35, 10.95it/s]
 23% 114/500 [00:09<00:34, 11.11it/s]
 23% 116/500 [00:09<00:33, 11.55it/s]
 24% 118/500 [00:10<00:33, 11.49it/s]
 24% 120/500 [00:10<00:34, 10.89it/s]
 24% 122/500 [00:10<00:36, 10.39it/s]
 25% 124/500 [00:10<00:33, 11.13it/s]
 25% 126/500 [00:10<00:31, 11.87it/s]
 26% 128/500 [00:10<00:28, 12.97it/s]
 26% 130/500 [00:11<00:31, 11.72it/s]
 26% 132/500 [00:11<00:36, 10.16it/s]
 27% 134/500 [00:11<00:35, 10.29it/s]
 27% 136/500 [00:11<00:32, 11.30it/s]
 28% 138/500 [00:11<00:29, 12.34it/s]
 28% 140/500 [00:11<00:30, 11.93it/s]
 28% 142/500 [00:12<00:33, 10.70it/s]
 29% 144/500 [00:12<00:34, 10.37it/s]
 29% 146/500 [00:12<00:32, 10.99it/s]
 30% 148/500 [00:12<00:30, 11.42it/s]
 30% 150/500 [00:12<00:29, 11.87it/s]
 30% 152/500 [00:13<00:28, 12.18it/s]
 31% 154/500 [00:13<00:29, 11.73it/s]
 31% 156/500 [00:13<00:28, 11.91it/s]
 32% 158/500 [00:13<00:28, 11.99it/s]
 32% 160/500 [00:13<00:28, 11.73it/s]
 32% 162/500 [00:13<00:29, 11.29it/s]
 33% 165/500 [00:14<00:25, 13.13it/s]
 33% 167/500 [00:14<00:27, 11.93it/s]
 34% 169/500 [00:14<00:28, 11.79it/s]
 34% 171/500 [00:14<00:28, 11.53it/s]
 35% 173/500 [00:14<00:29, 11.08it/s]
 35% 175/500 [00:15<00:28, 11.47it/s]
 35% 177/500 [00:15<00:27, 11.60it/s]
 36% 179/500 [00:15<00:26, 12.28it/s]
 36% 181/500 [00:15<00:25, 12.56it/s]
 37% 183/500 [00:15<00:30, 10.44it/s]
 37% 185/500 [00:15<00:28, 11.08it/s]
 37% 187/500 [00:16<00:25, 12.07it/s]
 38% 189/500 [00:16<00:28, 10.83it/s]
 38% 191/500 [00:16<00:27, 11.28it/s]
 39% 193/500 [00:16<00:26, 11.75it/s]
 39% 195/500 [00:16<00:24, 12.68it/s]
 39% 197/500 [00:16<00:23, 12.76it/s]
 40% 199/500 [00:17<00:25, 11.66it/s]
 40% 201/500 [00:17<00:23, 12.78it/s]
 41% 203/500 [00:17<00:24, 12.16it/s]
 41% 205/500 [00:17<00:23, 12.66it/s]
 41% 207/500 [00:17<00:26, 11.19it/s]
 42% 209/500 [00:17<00:25, 11.60it/s]
 42% 211/500 [00:18<00:25, 11.53it/s]
 43% 213/500 [00:18<00:25, 11.20it/s]
 43% 215/500 [00:18<00:26, 10.95it/s]
 43% 217/500 [00:18<00:24, 11.58it/s]
 44% 219/500 [00:18<00:23, 11.97it/s]
 44% 221/500 [00:18<00:22, 12.19it/s]
 45% 223/500 [00:19<00:24, 11.46it/s]
 45% 225/500 [00:19<00:25, 10.88it/s]
 45% 227/500 [00:19<00:22, 12.05it/s]
 46% 229/500 [00:19<00:21, 12.60it/s]
 46% 231/500 [00:19<00:25, 10.70it/s]
 47% 233/500 [00:19<00:21, 12.23it/s]
 47% 235/500 [00:20<00:22, 11.91it/s]
 47% 237/500 [00:20<00:22, 11.55it/s]
 48% 239/500 [00:20<00:21, 12.10it/s]
 48% 241/500 [00:20<00:20, 12.58it/s]
 49% 243/500 [00:20<00:20, 12.30it/s]
 49% 245/500 [00:20<00:21, 12.02it/s]
 49% 247/500 [00:21<00:21, 11.74it/s]
 50% 249/500 [00:21<00:23, 10.87it/s]
 50% 251/500 [00:21<00:23, 10.75it/s]
 51% 253/500 [00:21<00:21, 11.58it/s]
 51% 255/500 [00:21<00:23, 10.34it/s]
 51% 257/500 [00:22<00:23, 10.53it/s]
 52% 259/500 [00:22<00:22, 10.68it/s]
 52% 261/500 [00:22<00:23, 10.36it/s]
 53% 263/500 [00:22<00:21, 11.17it/s]
 53% 265/500 [00:22<00:22, 10.61it/s]
 53% 267/500 [00:23<00:21, 10.61it/s]
 54% 269/500 [00:23<00:20, 11.44it/s]
 54% 271/500 [00:23<00:20, 11.39it/s]
 55% 273/500 [00:23<00:19, 11.61it/s]
 55% 275/500 [00:23<00:19, 11.69it/s]
 55% 277/500 [00:23<00:19, 11.40it/s]
 56% 279/500 [00:24<00:18, 11.68it/s]
 56% 281/500 [00:24<00:19, 11.13it/s]
 57% 283/500 [00:24<00:20, 10.42it/s]
 57% 285/500 [00:24<00:21,  9.91it/s]
 57% 287/500 [00:24<00:20, 10.57it/s]
 58% 289/500 [00:25<00:19, 10.61it/s]
 58% 291/500 [00:25<00:18, 11.47it/s]
 59% 293/500 [00:25<00:18, 10.93it/s]
 59% 295/500 [00:25<00:16, 12.35it/s]
 59% 297/500 [00:25<00:17, 11.54it/s]
 60% 299/500 [00:25<00:16, 11.98it/s]
 60% 301/500 [00:26<00:18, 11.01it/s]
 61% 303/500 [00:26<00:16, 11.78it/s]
 61% 305/500 [00:26<00:16, 11.96it/s]
 61% 307/500 [00:26<00:17, 11.22it/s]
 62% 309/500 [00:26<00:16, 11.32it/s]
 62% 311/500 [00:26<00:16, 11.16it/s]
 63% 313/500 [00:27<00:17, 10.71it/s]
 63% 315/500 [00:27<00:15, 12.13it/s]
 63% 317/500 [00:27<00:14, 12.49it/s]
 64% 319/500 [00:27<00:16, 10.66it/s]
 64% 321/500 [00:27<00:15, 11.85it/s]
 65% 323/500 [00:27<00:16, 11.01it/s]
 65% 325/500 [00:28<00:14, 12.12it/s]

In [ ]:
!python src/train_modernbert.py \
    --model_name "answerdotai/ModernBERT-base" \
    --data_path "data/raw/aita_full.csv" \
    --output_dir "models/modernbert_base_full" \
    --batch_size 4 \
    --grad_accum 4 \
    --max_length 1024 \
    --lr 5e-6 \
    --eval_steps 50 \
    --patience 3 \
    --fp16

Streaming output truncated to the last 5000 lines.
 85% 4153/4882 [02:45<00:30, 24.25it/s]
 85% 4156/4882 [02:45<00:29, 24.47it/s]
 85% 4159/4882 [02:45<00:33, 21.67it/s]
 85% 4162/4882 [02:46<00:32, 22.23it/s]
 85% 4165/4882 [02:46<00:30, 23.83it/s]
 85% 4168/4882 [02:46<00:28, 24.73it/s]
 85% 4171/4882 [02:46<00:29, 23.93it/s]
 85% 4174/4882 [02:46<00:28, 24.84it/s]
 86% 4177/4882 [02:46<00:30, 23.27it/s]
 86% 4180/4882 [02:46<00:28, 24.74it/s]
 86% 4183/4882 [02:46<00:27, 25.24it/s]
 86% 4186/4882 [02:47<00:28, 24.51it/s]
 86% 4189/4882 [02:47<00:30, 22.95it/s]
 86% 4192/4882 [02:47<00:28, 24.14it/s]
 86% 4196/4882 [02:47<00:27, 25.26it/s]
 86% 4199/4882 [02:47<00:26, 25.59it/s]
 86% 4202/4882 [02:47<00:28, 24.06it/s]
 86% 4205/4882 [02:47<00:27, 24.66it/s]
 86% 4208/4882 [02:47<00:26, 25.83it/s]
 86% 4211/4882 [02:48<00:25, 26.52it/s]
 86% 4214/4882 [02:48<00:26, 25.13it/s]
 86% 4217/4882 [02:48<00:25, 26.05it/s]
 86% 4220/4882 [02:48<00:25, 26.25it/s]
 87% 4224/4882 [02:48<00:23, 27.88it/s]
 87% 4227/4882 [02:48<00:24, 27.12it/s]
 87% 4230/4882 [02:48<00:23, 27.22it/s]
 87% 4233/4882 [02:48<00:25, 25.53it/s]
 87% 4236/4882 [02:49<00:25, 25.02it/s]
 87% 4239/4882 [02:49<00:25, 25.28it/s]
 87% 4242/4882 [02:49<00:25, 25.42it/s]
 87% 4245/4882 [02:49<00:24, 26.09it/s]
 87% 4249/4882 [02:49<00:22, 27.86it/s]
 87% 4252/4882 [02:49<00:22, 28.42it/s]
 87% 4255/4882 [02:49<00:21, 28.71it/s]
 87% 4258/4882 [02:49<00:21, 29.06it/s]
 87% 4261/4882 [02:49<00:22, 28.18it/s]
 87% 4264/4882 [02:50<00:22, 27.50it/s]
 87% 4267/4882 [02:50<00:22, 27.85it/s]
 87% 4270/4882 [02:50<00:22, 27.24it/s]
 88% 4273/4882 [02:50<00:22, 26.58it/s]
 88% 4276/4882 [02:50<00:23, 26.22it/s]
 88% 4279/4882 [02:50<00:25, 23.92it/s]
 88% 4282/4882 [02:50<00:24, 24.10it/s]
 88% 4285/4882 [02:50<00:23, 25.37it/s]
 88% 4288/4882 [02:50<00:23, 25.16it/s]
 88% 4291/4882 [02:51<00:25, 23.45it/s]
 88% 4294/4882 [02:51<00:23, 24.59it/s]
 88% 4297/4882 [02:51<00:24, 23.79it/s]
 88% 4300/4882 [02:51<00:24, 23.58it/s]
 88% 4303/4882 [02:51<00:24, 24.06it/s]
 88% 4306/4882 [02:51<00:24, 23.66it/s]
 88% 4309/4882 [02:51<00:23, 24.82it/s]
 88% 4312/4882 [02:51<00:22, 25.31it/s]
 88% 4315/4882 [02:52<00:23, 24.32it/s]
 88% 4318/4882 [02:52<00:24, 22.65it/s]
 89% 4322/4882 [02:52<00:22, 24.98it/s]
 89% 4325/4882 [02:52<00:22, 24.71it/s]
 89% 4328/4882 [02:52<00:21, 25.28it/s]
 89% 4331/4882 [02:52<00:23, 23.90it/s]
 89% 4334/4882 [02:52<00:22, 24.34it/s]
 89% 4337/4882 [02:53<00:23, 23.57it/s]
 89% 4340/4882 [02:53<00:21, 24.65it/s]
 89% 4343/4882 [02:53<00:22, 23.56it/s]
 89% 4346/4882 [02:53<00:22, 23.96it/s]
 89% 4349/4882 [02:53<00:21, 25.38it/s]
 89% 4352/4882 [02:53<00:20, 26.48it/s]
 89% 4355/4882 [02:53<00:20, 25.14it/s]
 89% 4358/4882 [02:53<00:21, 24.52it/s]
 89% 4361/4882 [02:53<00:21, 23.74it/s]
 89% 4365/4882 [02:54<00:19, 25.93it/s]
 89% 4368/4882 [02:54<00:21, 24.26it/s]
 90% 4371/4882 [02:54<00:20, 24.60it/s]
 90% 4374/4882 [02:54<00:21, 23.98it/s]
 90% 4377/4882 [02:54<00:20, 24.44it/s]
 90% 4380/4882 [02:54<00:19, 25.10it/s]
 90% 4383/4882 [02:54<00:19, 25.42it/s]
 90% 4386/4882 [02:54<00:19, 24.86it/s]
 90% 4389/4882 [02:55<00:18, 26.12it/s]
 90% 4392/4882 [02:55<00:18, 26.47it/s]
 90% 4396/4882 [02:55<00:17, 27.88it/s]
 90% 4399/4882 [02:55<00:17, 26.95it/s]
 90% 4402/4882 [02:55<00:18, 25.95it/s]
 90% 4405/4882 [02:55<00:18, 25.21it/s]
 90% 4409/4882 [02:55<00:17, 27.17it/s]
 90% 4412/4882 [02:55<00:17, 26.23it/s]
 90% 4415/4882 [02:56<00:19, 24.00it/s]
 90% 4418/4882 [02:56<00:18, 24.72it/s]
 91% 4421/4882 [02:56<00:18, 25.55it/s]
 91% 4424/4882 [02:56<00:17, 25.99it/s]
 91% 4427/4882 [02:56<00:18, 24.88it/s]
 91% 4430/4882 [02:56<00:17, 25.87it/s]
 91% 4433/4882 [02:56<00:17, 25.00it/s]
 91% 4436/4882 [02:56<00:18, 23.63it/s]
 91% 4439/4882 [02:57<00:18, 24.42it/s]
 91% 4442/4882 [02:57<00:17, 25.41it/s]
 91% 4445/4882 [02:57<00:17, 24.82it/s]
 91% 4448/4882 [02:57<00:16, 26.09it/s]
 91% 4451/4882 [02:57<00:16, 25.75it/s]
 91% 4454/4882 [02:57<00:16, 26.53it/s]
 91% 4457/4882 [02:57<00:15, 26.92it/s]
 91% 4460/4882 [02:57<00:15, 27.43it/s]
 91% 4464/4882 [02:57<00:14, 28.78it/s]
 91% 4467/4882 [02:58<00:15, 26.42it/s]
 92% 4471/4882 [02:58<00:14, 27.56it/s]
 92% 4474/4882 [02:58<00:15, 27.11it/s]
 92% 4477/4882 [02:58<00:15, 25.56it/s]
 92% 4480/4882 [02:58<00:15, 26.55it/s]
 92% 4484/4882 [02:58<00:14, 27.26it/s]
 92% 4487/4882 [02:58<00:15, 25.52it/s]
 92% 4490/4882 [02:58<00:15, 26.04it/s]
 92% 4493/4882 [02:59<00:15, 25.47it/s]
 92% 4496/4882 [02:59<00:15, 25.37it/s]
 92% 4499/4882 [02:59<00:14, 25.67it/s]
 92% 4502/4882 [02:59<00:14, 25.52it/s]
 92% 4505/4882 [02:59<00:14, 26.53it/s]
 92% 4508/4882 [02:59<00:14, 25.59it/s]
 92% 4511/4882 [02:59<00:14, 26.14it/s]
 92% 4514/4882 [02:59<00:14, 26.19it/s]
 93% 4517/4882 [03:00<00:14, 26.02it/s]
 93% 4520/4882 [03:00<00:14, 24.96it/s]
 93% 4524/4882 [03:00<00:13, 26.67it/s]
 93% 4528/4882 [03:00<00:12, 27.49it/s]
 93% 4532/4882 [03:00<00:12, 28.70it/s]
 93% 4536/4882 [03:00<00:12, 28.34it/s]
 93% 4539/4882 [03:00<00:12, 26.87it/s]
 93% 4542/4882 [03:00<00:12, 27.63it/s]
 93% 4545/4882 [03:01<00:12, 27.60it/s]
 93% 4549/4882 [03:01<00:11, 28.27it/s]
 93% 4552/4882 [03:01<00:11, 27.89it/s]
 93% 4556/4882 [03:01<00:11, 29.00it/s]
 93% 4559/4882 [03:01<00:11, 27.36it/s]
 93% 4562/4882 [03:01<00:11, 26.73it/s]
 94% 4565/4882 [03:01<00:11, 26.47it/s]
 94% 4568/4882 [03:01<00:12, 25.39it/s]
 94% 4572/4882 [03:02<00:11, 27.00it/s]
 94% 4575/4882 [03:02<00:11, 26.18it/s]
 94% 4578/4882 [03:02<00:12, 25.25it/s]
 94% 4581/4882 [03:02<00:12, 24.10it/s]
 94% 4584/4882 [03:02<00:11, 25.50it/s]
 94% 4587/4882 [03:02<00:12, 24.58it/s]
 94% 4590/4882 [03:02<00:12, 23.13it/s]
 94% 4593/4882 [03:02<00:12, 23.96it/s]
 94% 4596/4882 [03:03<00:11, 24.18it/s]
 94% 4599/4882 [03:03<00:11, 24.90it/s]
 94% 4602/4882 [03:03<00:12, 22.67it/s]
 94% 4605/4882 [03:03<00:12, 22.94it/s]
 94% 4608/4882 [03:03<00:11, 24.48it/s]
 94% 4611/4882 [03:03<00:11, 23.60it/s]
 95% 4614/4882 [03:03<00:10, 24.77it/s]
 95% 4617/4882 [03:03<00:10, 25.72it/s]
 95% 4620/4882 [03:03<00:10, 26.18it/s]
 95% 4624/4882 [03:04<00:09, 27.22it/s]
 95% 4627/4882 [03:04<00:09, 27.41it/s]
 95% 4630/4882 [03:04<00:10, 25.16it/s]
 95% 4633/4882 [03:04<00:10, 23.25it/s]
 95% 4637/4882 [03:04<00:09, 24.99it/s]
 95% 4641/4882 [03:04<00:09, 26.59it/s]
 95% 4645/4882 [03:04<00:08, 27.13it/s]
 95% 4648/4882 [03:05<00:09, 24.76it/s]
 95% 4651/4882 [03:05<00:09, 24.15it/s]
 95% 4654/4882 [03:05<00:08, 25.48it/s]
 95% 4657/4882 [03:05<00:08, 25.53it/s]
 95% 4661/4882 [03:05<00:08, 26.76it/s]
 96% 4664/4882 [03:05<00:08, 26.13it/s]
 96% 4667/4882 [03:05<00:08, 26.58it/s]
 96% 4670/4882 [03:05<00:08, 26.48it/s]
 96% 4673/4882 [03:06<00:08, 25.99it/s]
 96% 4676/4882 [03:06<00:08, 24.01it/s]
 96% 4679/4882 [03:06<00:08, 22.65it/s]
 96% 4682/4882 [03:06<00:09, 21.96it/s]
 96% 4685/4882 [03:06<00:08, 22.53it/s]
 96% 4688/4882 [03:06<00:08, 23.46it/s]
 96% 4691/4882 [03:06<00:08, 23.49it/s]
 96% 4694/4882 [03:06<00:07, 23.82it/s]
 96% 4697/4882 [03:07<00:08, 22.90it/s]
 96% 4700/4882 [03:07<00:07, 23.82it/s]
 96% 4703/4882 [03:07<00:07, 22.86it/s]
 96% 4706/4882 [03:07<00:07, 23.71it/s]
 96% 4709/4882 [03:07<00:07, 23.95it/s]
 97% 4713/4882 [03:07<00:06, 26.46it/s]
 97% 4716/4882 [03:07<00:06, 24.52it/s]
 97% 4719/4882 [03:08<00:06, 25.29it/s]
 97% 4722/4882 [03:08<00:06, 24.78it/s]
 97% 4725/4882 [03:08<00:06, 25.16it/s]
 97% 4728/4882 [03:08<00:06, 25.19it/s]
 97% 4732/4882 [03:08<00:05, 26.14it/s]
 97% 4735/4882 [03:08<00:05, 25.09it/s]
 97% 4738/4882 [03:08<00:05, 25.85it/s]
 97% 4741/4882 [03:08<00:05, 24.62it/s]
 97% 4744/4882 [03:08<00:05, 25.17it/s]
 97% 4747/4882 [03:09<00:05, 24.66it/s]
 97% 4750/4882 [03:09<00:05, 25.11it/s]
 97% 4753/4882 [03:09<00:05, 23.92it/s]
 97% 4756/4882 [03:09<00:05, 23.52it/s]
 97% 4759/4882 [03:09<00:05, 24.40it/s]
 98% 4762/4882 [03:09<00:04, 24.16it/s]
 98% 4766/4882 [03:09<00:04, 26.28it/s]
 98% 4769/4882 [03:10<00:04, 23.59it/s]
 98% 4772/4882 [03:10<00:04, 23.08it/s]
 98% 4775/4882 [03:10<00:04, 22.78it/s]
 98% 4778/4882 [03:10<00:04, 23.17it/s]
 98% 4781/4882 [03:10<00:04, 23.34it/s]
 98% 4784/4882 [03:10<00:04, 23.13it/s]
 98% 4787/4882 [03:10<00:04, 23.00it/s]
 98% 4790/4882 [03:10<00:03, 23.10it/s]
 98% 4793/4882 [03:11<00:03, 24.80it/s]
 98% 4797/4882 [03:11<00:03, 27.22it/s]
 98% 4800/4882 [03:11<00:03, 26.64it/s]
 98% 4803/4882 [03:11<00:03, 24.41it/s]
 98% 4806/4882 [03:11<00:03, 23.71it/s]
 99% 4810/4882 [03:11<00:02, 25.15it/s]
 99% 4814/4882 [03:11<00:02, 26.77it/s]
 99% 4817/4882 [03:11<00:02, 26.31it/s]
 99% 4820/4882 [03:12<00:02, 26.27it/s]
 99% 4823/4882 [03:12<00:02, 27.05it/s]
 99% 4827/4882 [03:12<00:01, 27.99it/s]
 99% 4830/4882 [03:12<00:01, 28.25it/s]
 99% 4833/4882 [03:12<00:01, 27.73it/s]
 99% 4836/4882 [03:12<00:01, 24.43it/s]
 99% 4839/4882 [03:12<00:01, 23.89it/s]
 99% 4842/4882 [03:12<00:01, 23.66it/s]
 99% 4846/4882 [03:13<00:01, 26.33it/s]
 99% 4849/4882 [03:13<00:01, 24.24it/s]
 99% 4852/4882 [03:13<00:01, 24.85it/s]
 99% 4855/4882 [03:13<00:01, 24.08it/s]
100% 4858/4882 [03:13<00:00, 25.48it/s]
100% 4861/4882 [03:13<00:00, 25.97it/s]
100% 4864/4882 [03:13<00:00, 25.48it/s]
100% 4867/4882 [03:13<00:00, 24.47it/s]
100% 4870/4882 [03:14<00:00, 23.56it/s]
100% 4873/4882 [03:14<00:00, 23.84it/s]
100% 4877/4882 [03:14<00:00, 25.96it/s]
100% 4880/4882 [03:14<00:00, 26.41it/s]
{'eval_loss': '0.6724', 'eval_accuracy': '0.603', 'eval_f1_macro': '0.4996', 'eval_precision_macro': '0.4996', 'eval_recall_macro': '0.4996', 'eval_runtime': '194.5', 'eval_samples_per_second': '100.4', 'eval_steps_per_second': '25.09', 'epoch': '0.07544'}

  2% 200/13255 [14:52<1:48:10,  2.01it/s]

Writing model shards:   0% 0/1 [00:00<?, ?it/s]
Writing model shards: 100% 1/1 [00:00<00:00,  1.40it/s]
{'loss': '2.762', 'grad_norm': '15.25', 'learning_rate': '5.631e-07', 'epoch': '0.08487'}
{'loss': '2.826', 'grad_norm': '27.55', 'learning_rate': '6.259e-07', 'epoch': '0.0943'}
  2% 250/13255 [15:24<1:49:57,  1.97it/s]
  0% 0/4882 [00:00<?, ?it/s]
  0% 4/4882 [00:00<02:02, 39.96it/s]
  0% 8/4882 [00:00<02:35, 31.25it/s]
  0% 12/4882 [00:00<02:58, 27.27it/s]
  0% 15/4882 [00:00<02:58, 27.29it/s]
  0% 19/4882 [00:00<02:50, 28.56it/s]
  0% 22/4882 [00:00<03:02, 26.65it/s]
  1% 25/4882 [00:00<03:09, 25.70it/s]
  1% 28/4882 [00:01<03:03, 26.40it/s]
  1% 31/4882 [00:01<02:58, 27.22it/s]
  1% 34/4882 [00:01<03:01, 26.71it/s]
  1% 37/4882 [00:01<03:03, 26.44it/s]
  1% 40/4882 [00:01<03:15, 24.73it/s]
  1% 43/4882 [00:01<03:12, 25.17it/s]
  1% 46/4882 [00:01<03:12, 25.08it/s]
  1% 49/4882 [00:01<03:17, 24.45it/s]
  1% 52/4882 [00:02<03:29, 23.06it/s]
  1% 55/4882 [00:02<03:18, 24.31it/s]
  1% 58/4882 [00:02<03:09, 25.43it/s]
  1% 62/4882 [00:02<03:01, 26.52it/s]
  1% 65/4882 [00:02<02:58, 26.96it/s]
  1% 68/4882 [00:02<03:01, 26.47it/s]
  1% 71/4882 [00:02<02:58, 26.91it/s]
  2% 74/4882 [00:02<03:01, 26.47it/s]
  2% 77/4882 [00:02<03:01, 26.45it/s]
  2% 80/4882 [00:03<03:00, 26.63it/s]
  2% 83/4882 [00:03<03:08, 25.43it/s]
  2% 86/4882 [00:03<03:02, 26.23it/s]
  2% 89/4882 [00:03<03:10, 25.12it/s]
  2% 92/4882 [00:03<03:08, 25.42it/s]
  2% 95/4882 [00:03<03:11, 24.97it/s]
  2% 99/4882 [00:03<02:59, 26.70it/s]
  2% 102/4882 [00:03<03:01, 26.31it/s]
  2% 105/4882 [00:04<03:18, 24.02it/s]
  2% 108/4882 [00:04<03:29, 22.84it/s]
  2% 111/4882 [00:04<03:23, 23.40it/s]
  2% 114/4882 [00:04<03:16, 24.31it/s]
  2% 117/4882 [00:04<03:09, 25.09it/s]
  2% 120/4882 [00:04<03:09, 25.14it/s]
  3% 123/4882 [00:04<03:06, 25.52it/s]
  3% 126/4882 [00:04<03:06, 25.44it/s]
  3% 129/4882 [00:05<03:11, 24.80it/s]
  3% 132/4882 [00:05<03:10, 24.90it/s]
  3% 135/4882 [00:05<03:17, 24.03it/s]
  3% 138/4882 [00:05<03:20, 23.69it/s]
  3% 141/4882 [00:05<03:13, 24.48it/s]
  3% 144/4882 [00:05<03:16, 24.16it/s]
  3% 147/4882 [00:05<03:19, 23.76it/s]
  3% 150/4882 [00:05<03:29, 22.57it/s]
  3% 153/4882 [00:06<03:22, 23.39it/s]
  3% 156/4882 [00:06<03:11, 24.71it/s]
  3% 159/4882 [00:06<03:23, 23.18it/s]
  3% 162/4882 [00:06<03:32, 22.25it/s]
  3% 165/4882 [00:06<03:23, 23.13it/s]
  3% 168/4882 [00:06<03:16, 24.03it/s]
  4% 172/4882 [00:06<03:01, 25.97it/s]
  4% 175/4882 [00:06<03:22, 23.28it/s]
  4% 178/4882 [00:07<03:16, 23.96it/s]
  4% 181/4882 [00:07<03:17, 23.82it/s]
  4% 184/4882 [00:07<03:07, 25.02it/s]
  4% 187/4882 [00:07<03:19, 23.54it/s]
  4% 190/4882 [00:07<03:17, 23.75it/s]
  4% 193/4882 [00:07<03:10, 24.63it/s]
  4% 196/4882 [00:07<03:24, 22.95it/s]
  4% 200/4882 [00:07<03:09, 24.77it/s]
  4% 203/4882 [00:08<03:11, 24.38it/s]
  4% 206/4882 [00:08<03:07, 24.87it/s]
  4% 209/4882 [00:08<03:08, 24.75it/s]
  4% 212/4882 [00:08<03:28, 22.45it/s]
  4% 215/4882 [00:08<03:17, 23.57it/s]
  4% 218/4882 [00:08<03:21, 23.19it/s]
  5% 221/4882 [00:08<03:21, 23.17it/s]
  5% 224/4882 [00:09<03:39, 21.26it/s]
  5% 227/4882 [00:09<03:21, 23.07it/s]
  5% 230/4882 [00:09<03:15, 23.79it/s]
  5% 233/4882 [00:09<03:08, 24.65it/s]
  5% 236/4882 [00:09<03:22, 22.97it/s]
  5% 239/4882 [00:09<03:16, 23.61it/s]
  5% 242/4882 [00:09<03:14, 23.86it/s]
  5% 245/4882 [00:09<03:23, 22.80it/s]
  5% 248/4882 [00:10<03:21, 23.05it/s]
  5% 251/4882 [00:10<03:23, 22.78it/s]
  5% 254/4882 [00:10<03:09, 24.36it/s]
  5% 257/4882 [00:10<03:12, 24.01it/s]
  5% 260/4882 [00:10<03:18, 23.24it/s]
  5% 264/4882 [00:10<03:10, 24.18it/s]
  5% 267/4882 [00:10<03:06, 24.80it/s]
  6% 270/4882 [00:10<03:01, 25.36it/s]
  6% 274/4882 [00:11<02:49, 27.13it/s]
  6% 277/4882 [00:11<03:01, 25.38it/s]
  6% 280/4882 [00:11<03:15, 23.57it/s]
  6% 283/4882 [00:11<03:13, 23.82it/s]
  6% 286/4882 [00:11<03:19, 23.08it/s]
  6% 289/4882 [00:11<03:16, 23.35it/s]
  6% 292/4882 [00:11<03:04, 24.81it/s]
  6% 295/4882 [00:11<02:59, 25.59it/s]
  6% 298/4882 [00:12<02:59, 25.57it/s]
  6% 302/4882 [00:12<02:46, 27.54it/s]
  6% 306/4882 [00:12<02:43, 27.95it/s]
  6% 309/4882 [00:12<02:44, 27.83it/s]
  6% 312/4882 [00:12<02:46, 27.50it/s]
  6% 316/4882 [00:12<02:37, 29.00it/s]
  7% 319/4882 [00:12<02:38, 28.79it/s]
  7% 322/4882 [00:12<02:43, 27.92it/s]
  7% 325/4882 [00:13<02:43, 27.96it/s]
  7% 328/4882 [00:13<02:50, 26.75it/s]
  7% 331/4882 [00:13<02:49, 26.90it/s]
  7% 334/4882 [00:13<02:54, 26.12it/s]
  7% 337/4882 [00:13<03:07, 24.27it/s]
  7% 340/4882 [00:13<03:15, 23.28it/s]
  7% 343/4882 [00:13<03:20, 22.63it/s]
  7% 346/4882 [00:13<03:17, 22.95it/s]
  7% 349/4882 [00:14<03:27, 21.80it/s]
  7% 352/4882 [00:14<03:14, 23.29it/s]
  7% 355/4882 [00:14<03:11, 23.68it/s]
  7% 358/4882 [00:14<03:15, 23.19it/s]
  7% 361/4882 [00:14<03:05, 24.32it/s]
  7% 364/4882 [00:14<03:01, 24.87it/s]
  8% 367/4882 [00:14<03:10, 23.70it/s]
  8% 370/4882 [00:14<03:05, 24.31it/s]
  8% 373/4882 [00:15<03:04, 24.38it/s]
  8% 376/4882 [00:15<03:13, 23.32it/s]
  8% 379/4882 [00:15<03:02, 24.73it/s]
  8% 382/4882 [00:15<03:03, 24.58it/s]
  8% 385/4882 [00:15<03:00, 24.89it/s]
  8% 389/4882 [00:15<02:51, 26.25it/s]
  8% 392/4882 [00:15<02:51, 26.13it/s]
  8% 395/4882 [00:15<03:04, 24.37it/s]
  8% 398/4882 [00:16<03:07, 23.87it/s]
  8% 401/4882 [00:16<03:03, 24.36it/s]
  8% 404/4882 [00:16<03:03, 24.40it/s]
  8% 407/4882 [00:16<02:59, 24.88it/s]
  8% 410/4882 [00:16<03:08, 23.78it/s]
  8% 413/4882 [00:16<03:03, 24.36it/s]
  9% 416/4882 [00:16<03:20, 22.27it/s]
  9% 419/4882 [00:16<03:12, 23.21it/s]
  9% 422/4882 [00:17<03:12, 23.19it/s]
  9% 425/4882 [00:17<03:08, 23.60it/s]
  9% 428/4882 [00:17<03:11, 23.22it/s]
  9% 431/4882 [00:17<03:20, 22.21it/s]
  9% 434/4882 [00:17<03:07, 23.78it/s]
  9% 437/4882 [00:17<02:56, 25.23it/s]
  9% 440/4882 [00:17<02:53, 25.59it/s]
  9% 443/4882 [00:17<02:55, 25.27it/s]
  9% 446/4882 [00:18<03:09, 23.41it/s]
  9% 449/4882 [00:18<03:04, 24.01it/s]
  9% 452/4882 [00:18<02:58, 24.83it/s]
  9% 455/4882 [00:18<02:56, 25.12it/s]
  9% 458/4882 [00:18<02:52, 25.64it/s]
  9% 461/4882 [00:18<03:05, 23.80it/s]
 10% 464/4882 [00:18<02:57, 24.89it/s]
 10% 467/4882 [00:18<02:55, 25.13it/s]
 10% 470/4882 [00:19<02:56, 25.01it/s]
 10% 473/4882 [00:19<02:48, 26.11it/s]
 10% 476/4882 [00:19<02:47, 26.34it/s]
 10% 480/4882 [00:19<02:39, 27.59it/s]
 10% 484/4882 [00:19<02:38, 27.72it/s]
 10% 487/4882 [00:19<02:57, 24.79it/s]
 10% 490/4882 [00:19<03:00, 24.35it/s]
 10% 493/4882 [00:19<02:51, 25.63it/s]
 10% 496/4882 [00:20<02:57, 24.71it/s]
 10% 499/4882 [00:20<03:09, 23.16it/s]
 10% 502/4882 [00:20<02:58, 24.57it/s]
 10% 506/4882 [00:20<02:45, 26.52it/s]
 10% 510/4882 [00:20<02:32, 28.63it/s]
 11% 513/4882 [00:20<02:47, 26.01it/s]
 11% 516/4882 [00:20<02:53, 25.11it/s]
 11% 519/4882 [00:20<02:49, 25.76it/s]
 11% 522/4882 [00:21<02:45, 26.41it/s]
 11% 525/4882 [00:21<02:50, 25.57it/s]
 11% 528/4882 [00:21<02:46, 26.20it/s]
 11% 531/4882 [00:21<02:49, 25.66it/s]
 11% 534/4882 [00:21<02:45, 26.29it/s]
 11% 537/4882 [00:21<02:50, 25.48it/s]
 11% 540/4882 [00:21<03:00, 24.03it/s]
 11% 543/4882 [00:21<02:50, 25.41it/s]
 11% 546/4882 [00:21<02:57, 24.45it/s]
 11% 549/4882 [00:22<02:58, 24.30it/s]
 11% 552/4882 [00:22<02:51, 25.24it/s]
 11% 555/4882 [00:22<02:57, 24.33it/s]
 11% 558/4882 [00:22<03:11, 22.59it/s]
 11% 561/4882 [00:22<03:05, 23.31it/s]
 12% 564/4882 [00:22<03:14, 22.24it/s]
 12% 567/4882 [00:22<03:22, 21.34it/s]
 12% 571/4882 [00:23<03:01, 23.71it/s]
 12% 574/4882 [00:23<03:01, 23.76it/s]
 12% 577/4882 [00:23<02:56, 24.41it/s]
 12% 581/4882 [00:23<02:46, 25.86it/s]
 12% 584/4882 [00:23<02:51, 25.12it/s]
 12% 587/4882 [00:23<02:45, 25.89it/s]
 12% 590/4882 [00:23<02:55, 24.47it/s]
 12% 594/4882 [00:23<02:46, 25.77it/s]
 12% 597/4882 [00:24<03:01, 23.66it/s]
 12% 600/4882 [00:24<03:04, 23.25it/s]
 12% 603/4882 [00:24<03:00, 23.70it/s]
 12% 606/4882 [00:24<03:06, 22.98it/s]
 12% 610/4882 [00:24<02:52, 24.74it/s]
 13% 614/4882 [00:24<02:40, 26.62it/s]
 13% 617/4882 [00:24<02:40, 26.54it/s]
 13% 620/4882 [00:25<02:45, 25.79it/s]
 13% 623/4882 [00:25<02:45, 25.79it/s]
 13% 626/4882 [00:25<02:39, 26.61it/s]
 13% 629/4882 [00:25<02:44, 25.87it/s]
 13% 632/4882 [00:25<02:47, 25.37it/s]
 13% 635/4882 [00:25<02:45, 25.70it/s]
 13% 638/4882 [00:25<02:40, 26.48it/s]
 13% 641/4882 [00:25<02:48, 25.18it/s]
 13% 644/4882 [00:25<02:42, 26.01it/s]
 13% 647/4882 [00:26<02:40, 26.42it/s]
 13% 650/4882 [00:26<02:59, 23.51it/s]
 13% 654/4882 [00:26<02:56, 23.99it/s]
 13% 657/4882 [00:26<02:59, 23.48it/s]
 14% 660/4882 [00:26<02:51, 24.64it/s]
 14% 663/4882 [00:26<02:42, 25.91it/s]
 14% 666/4882 [00:26<02:48, 25.03it/s]
 14% 670/4882 [00:26<02:39, 26.42it/s]
 14% 673/4882 [00:27<02:38, 26.48it/s]
 14% 676/4882 [00:27<02:43, 25.80it/s]
 14% 679/4882 [00:27<02:37, 26.65it/s]
 14% 682/4882 [00:27<02:46, 25.18it/s]
 14% 685/4882 [00:27<02:54, 24.04it/s]
 14% 688/4882 [00:27<02:57, 23.68it/s]
 14% 691/4882 [00:27<02:46, 25.19it/s]
 14% 694/4882 [00:27<02:39, 26.28it/s]
 14% 697/4882 [00:28<02:36, 26.81it/s]
 14% 700/4882 [00:28<02:44, 25.35it/s]
 14% 704/4882 [00:28<02:29, 27.91it/s]
 14% 707/4882 [00:28<02:34, 27.01it/s]
 15% 710/4882 [00:28<02:43, 25.58it/s]
 15% 713/4882 [00:28<02:36, 26.61it/s]
 15% 716/4882 [00:28<02:36, 26.64it/s]
 15% 719/4882 [00:28<02:34, 27.03it/s]
 15% 722/4882 [00:29<03:03, 22.68it/s]
 15% 725/4882 [00:29<02:58, 23.24it/s]
 15% 728/4882 [00:29<02:51, 24.17it/s]
 15% 731/4882 [00:29<02:51, 24.19it/s]
 15% 734/4882 [00:29<02:48, 24.67it/s]
 15% 737/4882 [00:29<02:59, 23.11it/s]
 15% 740/4882 [00:29<02:57, 23.30it/s]
 15% 743/4882 [00:29<02:56, 23.51it/s]
 15% 746/4882 [00:30<02:47, 24.66it/s]
 15% 749/4882 [00:30<02:42, 25.45it/s]
 15% 752/4882 [00:30<02:46, 24.81it/s]
 15% 755/4882 [00:30<02:56, 23.35it/s]
 16% 758/4882 [00:30<02:57, 23.25it/s]
 16% 761/4882 [00:30<03:02, 22.63it/s]
 16% 764/4882 [00:30<02:53, 23.77it/s]
 16% 767/4882 [00:30<02:58, 23.08it/s]
 16% 770/4882 [00:31<02:53, 23.69it/s]
 16% 773/4882 [00:31<02:58, 23.06it/s]
 16% 776/4882 [00:31<02:50, 24.15it/s]
 16% 779/4882 [00:31<02:51, 23.93it/s]
 16% 782/4882 [00:31<02:41, 25.45it/s]
 16% 785/4882 [00:31<02:35, 26.39it/s]
 16% 788/4882 [00:31<02:31, 26.96it/s]
 16% 791/4882 [00:31<02:32, 26.81it/s]
 16% 794/4882 [00:31<02:41, 25.37it/s]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [10]:
import os
from google.colab import userdata

# 1. Fetch credentials securely from Colab Secrets
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')
GITHUB_USERNAME = userdata.get('GITHUB_USERNAME')

# 2. Set your repository details
REPO_NAME = "r-AITA_classifier"            # e.g., "aita-classification"
REPO_BRANCH = "main"                     # or "master"
COMMIT_MSG = "Add modernbert training script with W&B support"
USER_EMAIL = "marvin.cy.wong@gmail.com"    # Your GitHub email

# 3. Configure local Git identity
!git config --global user.name "{GITHUB_USERNAME}"
!git config --global user.email "{USER_EMAIL}"

# 4. Change directory to your cloned repository folder
# (If your script is in /content, move into /content/your-repo-name first)
%cd /content/{REPO_NAME}

# 5. Add, Commit, and Push
!git add notebooks/Reddit_AITA_Training.ipynb
!git commit -m "{Modernbert training}"

# Push using the token in the URL for authentication
!git push https://{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git {REPO_BRANCH}

/content/r-AITA_classifier
fatal: pathspec 'notebooks/Reddit_AITA_Training.ipynb' did not match any files
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Everything up-to-date

## Topic Modeling

In [ ]:
results_df = pd.read_csv('data/raw/test_set_full.csv')
results_df.head(5)

,id,timestamp,title,body,edited,verdict,score,num_comments,is_asshole
0,9p5rq3,1.539835e+09,AITA for not wanting to move in together with ...,She's (24F) a student and I (30M) have worked ...,1539835524.0,not the asshole,8,25.0,0
1,d86cwz,1.569244e+09,AITA for thinking that an anniversary present ...,So this happened last night and I once again f...,False,not the asshole,18,27.0,0
2,bbgjfi,1.554862e+09,WIBTA If I didn't tell my friend I got a new car?,\n\nSo 3 weeks ago I got into a head on car a...,False,not the asshole,8,17.0,0
3,clq19y,1.564879e+09,AITA for competing in the women’s category for...,First- I’m an ultramarathoner/triathlete in my...,False,not the asshole,9,43.0,0
4,e0dwom,1.574489e+09,WIBTA if I moved away to fix my life,\n\nI'm the mother of two little girls. Their ...,1574491853.0,not the asshole,11,35.0,0

In [ ]:
import os
import pandas as pd
from bertopic import BERTopic
from sklearn.metrics import f1_score

# 0. Suppress tokenizer parallelism warnings
os.environ["TOKENIZERS_PARALLELISM"] = "false"

# 1. Ensure 'clean_full_text' exists by combining title + body
results_df['title'] = results_df['title'].fillna("").astype(str)
results_df['body'] = results_df['body'].fillna("").astype(str)
results_df['clean_full_text'] = (results_df['title'] + " " + results_df['body']).str.strip()

# 2. Initialize BERTopic (Will automatically use GPU if available)
print("Initializing BERTopic and generating embeddings...")
topic_model = BERTopic(embedding_model="all-MiniLM-L6-v2", calculate_probabilities=False)

# 3. Extract topics
docs = results_df['clean_full_text'].tolist()
topics, _ = topic_model.fit_transform(docs)

# 4. Map topics back to DataFrame safely
results_df['topic_id'] = topics

# Generate readable names for the clusters
topic_labels = topic_model.generate_topic_labels(nr_words=3, topic_prefix=True, separator="_")
topic_model.set_topic_labels(topic_labels)

# EXTRACT AS DICTIONARY: Grab the topic info and zip the IDs to the Custom Names
topic_info = topic_model.get_topic_info()
topic_mapping = dict(zip(topic_info['Topic'], topic_info['CustomName']))

# Map the dictionary to your dataframe
results_df['topic_name'] = results_df['topic_id'].map(topic_mapping)

# View what BERTopic discovered
print("\n=== Discovered Topics Overview ===")
display(topic_info.head(10))

# Save the BERTopic cluster definitions (Topic IDs, Counts, Keywords)
topic_info.to_csv("bertopic_cluster_definitions.csv", index=False)

Initializing BERTopic and generating embeddings...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

=== Discovered Topics Overview ===

,Topic,Count,Name,CustomName,Representation,Representative_Docs
0,-1,9192,-1_and_to_the_my,-1_and_to_the,"[and, to, the, my, he, that, me, for, it, of]",[AITA for banning my brother in law from my ho...
1,0,505,0_wedding_married_we_be,0_wedding_married_we,"[wedding, married, we, be, my, family, to, the...",[WIBTA if I chose to be a guest at my friend's...
2,1,446,1_dog_dogs_puppy_the,1_dog_dogs_puppy,"[dog, dogs, puppy, the, and, my, they, to, her...",[AITA For not taking care of my family's new d...
3,2,417,2_her_she_friends_me,2_her_she_friends,"[her, she, friends, me, we, was, friend, with,...",[AITA for snapping on my (25F) best friend (30...
4,3,389,3_christmas_family_birthday_my,3_christmas_family_birthday,"[christmas, family, birthday, my, go, year, pa...",[AITA for ruining my in-law's Christmas schedu...
5,4,328,4_class_teacher_grade_the,4_class_teacher_grade,"[class, teacher, grade, the, school, project, ...",[AITA for basically telling my math teacher he...
6,5,324,5_gift_gifts_christmas_for,5_gift_gifts_christmas,"[gift, gifts, christmas, for, it, buy, present...",[AITA for feeling disappointed in my Birthday ...
7,6,257,6_dad_father_him_he,6_dad_father_him,"[dad, father, him, he, my, mom, his, me, was, ...",[AITA for trying to get my parents to divorce?...
8,7,235,7_work_shift_job_boss,7_work_shift_job,"[work, shift, job, boss, manager, shifts, week...",[AITA for quitting my job over text? I worked ...
9,8,214,8_photos_pictures_instagram_photo,8_photos_pictures_instagram,"[photos, pictures, instagram, photo, picture, ...",[AITA for embarrassing my friend in public in ...

## Roberta Training

In [ ]:
import os
from google.colab import files

# Create the expected folder structure
os.makedirs("data/raw", exist_ok=True)

# Upload your CSV
uploaded = files.upload()

# Move the uploaded file to data/raw/
for filename in uploaded.keys():
    os.rename(filename, f"data/raw/{filename}")

Saving aita_full.csv to aita_full.csv

In [ ]:
!python src/train_deberta.py \
  --model_name roberta-base \
  --data_path data/raw/aita_full.csv \
  --epochs 3 \
  --batch_size 16 \
  --lr 2e-5 \
  --output_dir models/roberta_aita_full

=== Fine-Tuning roberta-base ===
Loading raw data from 'data/raw/aita_full.csv'...
Applying undersampling to balance training set (50/50 split)...
Balanced Train set size: 53020 | Test set size (natural ratio): 19525
Loading tokenizer & model weights for 'roberta-base'...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 197/197 [00:00<00:00, 4723.86it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.bias               | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
classifier.dense.weight    | MISSING    |
classifier.dense.bias      | MISSING    |
classifier.out_proj.bias   | MISSING    |
classifier.out_proj.weight | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Confirmed active architecture type: 'roberta'
Tokenizing datasets...
Map: 100% 53020/53020 [00:15<00:00, 3433.19 examples/s]
Map: 100% 19525/19525 [00:05<00:00, 3359.45 examples/s]

--- Data Sample Preview ---
Sample Label: 0
Sample Text:
TITLE: AITA for wanting to quit my adult kickball team?
STORY: I recently joined a local adult kickball league for fun. Nothing serious. There are ten games, ten teams, no tournament. At the fifth gam...
---------------------------

[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting Fine-Tuning Process...
{'loss': '0.6857', 'grad_norm': '2.332', 'learning_rate': '9.849e-07', 'epoch': '0.01509'}
{'loss': '0.6745', 'grad_norm': '1.287', 'learning_rate': '1.99e-06', 'epoch': '0.03018'}
{'loss': '0.6693', 'grad_norm': '2.791', 'learning_rate': '2.995e-06', 'epoch': '0.04526'}
{'loss': '0.6735', 'grad_norm': '1.803', 'learning_rate': '4e-06', 'epoch': '0.06035'}
{'loss': '0.6732', 'grad_norm': '2.857', 'learning_rate': '5.005e-06', 'epoch': '0.07544'}
{'loss': '0.6737', 'grad_norm': '2.858', 'learning_rate': '6.01e-06', 'epoch': '0.09053'}
{'loss': '0.67', 'grad_norm': '3.583', 'learning_rate': '7.015e-06', 'epoch': '0.1056'}
{'loss': '0.6805', 'grad_norm': '5.246', 'learning_rate': '8.02e-06', 'epoch': '0.1207'}
{'loss': '0.666', 'grad_norm': '3.04', 'learning_rate': '9.025e-06', 'epoch': '0.1358'}
{'loss': '0.656', 'grad_norm': '8.799', 'learning_rate': '1.003e-05', 'epoch': '0.1509'}
{'loss': '0.654', 'grad_norm': '7.137', 'learning_rate': '1.104e-05', 'epoch': '0.166'}
{'loss': '0.6734', 'grad_norm': '6.216', 'learning_rate': '1.204e-05', 'epoch': '0.1811'}
{'loss': '0.6655', 'grad_norm': '3.687', 'learning_rate': '1.305e-05', 'epoch': '0.1961'}
{'loss': '0.6589', 'grad_norm': '2.768', 'learning_rate': '1.405e-05', 'epoch': '0.2112'}
{'loss': '0.6827', 'grad_norm': '8.45', 'learning_rate': '1.506e-05', 'epoch': '0.2263'}
{'loss': '0.661', 'grad_norm': '6.168', 'learning_rate': '1.606e-05', 'epoch': '0.2414'}
{'loss': '0.6636', 'grad_norm': '3.647', 'learning_rate': '1.707e-05', 'epoch': '0.2565'}
{'loss': '0.6498', 'grad_norm': '4.684', 'learning_rate': '1.807e-05', 'epoch': '0.2716'}
{'loss': '0.6595', 'grad_norm': '2.41', 'learning_rate': '1.908e-05', 'epoch': '0.2867'}
{'loss': '0.6538', 'grad_norm': '5.306', 'learning_rate': '1.999e-05', 'epoch': '0.3018'}
{'loss': '0.6645', 'grad_norm': '2.982', 'learning_rate': '1.988e-05', 'epoch': '0.3168'}
{'loss': '0.6639', 'grad_norm': '1.927', 'learning_rate': '1.977e-05', 'epoch': '0.3319'}
{'loss': '0.6497', 'grad_norm': '5.952', 'learning_rate': '1.966e-05', 'epoch': '0.347'}
{'loss': '0.6499', 'grad_norm': '7.511', 'learning_rate': '1.954e-05', 'epoch': '0.3621'}
{'loss': '0.6512', 'grad_norm': '2.891', 'learning_rate': '1.943e-05', 'epoch': '0.3772'}
{'loss': '0.6409', 'grad_norm': '4.449', 'learning_rate': '1.932e-05', 'epoch': '0.3923'}
{'loss': '0.6523', 'grad_norm': '3.164', 'learning_rate': '1.921e-05', 'epoch': '0.4074'}
{'loss': '0.6629', 'grad_norm': '10.98', 'learning_rate': '1.91e-05', 'epoch': '0.4225'}
{'loss': '0.6586', 'grad_norm': '2.643', 'learning_rate': '1.899e-05', 'epoch': '0.4375'}
{'loss': '0.6566', 'grad_norm': '2.308', 'learning_rate': '1.887e-05', 'epoch': '0.4526'}
{'loss': '0.6687', 'grad_norm': '3.752', 'learning_rate': '1.876e-05', 'epoch': '0.4677'}
{'loss': '0.636', 'grad_norm': '5.413', 'learning_rate': '1.865e-05', 'epoch': '0.4828'}
{'loss': '0.6493', 'grad_norm': '3.399', 'learning_rate': '1.854e-05', 'epoch': '0.4979'}
{'loss': '0.6254', 'grad_norm': '10.28', 'learning_rate': '1.843e-05', 'epoch': '0.513'}
{'loss': '0.654', 'grad_norm': '2.962', 'learning_rate': '1.831e-05', 'epoch': '0.5281'}
{'loss': '0.6451', 'grad_norm': '4.548', 'learning_rate': '1.82e-05', 'epoch': '0.5432'}
{'loss': '0.61', 'grad_norm': '5.234', 'learning_rate': '1.809e-05', 'epoch': '0.5582'}
{'loss': '0.6513', 'grad_norm': '2.641', 'learning_rate': '1.798e-05', 'epoch': '0.5733'}
{'loss': '0.6367', 'grad_norm': '6.834', 'learning_rate': '1.787e-05', 'epoch': '0.5884'}
{'loss': '0.6426', 'grad_norm': '5.687', 'learning_rate': '1.776e-05', 'epoch': '0.6035'}
{'loss': '0.6436', 'grad_norm': '4.378', 'learning_rate': '1.764e-05', 'epoch': '0.6186'}
{'loss': '0.6436', 'grad_norm': '3.266', 'learning_rate': '1.753e-05', 'epoch': '0.6337'}
{'loss': '0.6468', 'grad_norm': '3.803', 'learning_rate': '1.742e-05', 'epoch': '0.6488'}
{'loss': '0.6482', 'grad_norm': '3.054', 'learning_rate': '1.731e-05', 'epoch': '0.6639'}
{'loss': '0.6382', 'grad_norm': '3.981', 'learning_rate': '1.72e-05', 'epoch': '0.6789'}
{'loss': '0.6337', 'grad_norm': '7.179', 'learning_rate': '1.709e-05', 'epoch': '0.694'}
{'loss': '0.6268', 'grad_norm': '4.527', 'learning_rate': '1.697e-05', 'epoch': '0.7091'}
{'loss': '0.6375', 'grad_norm': '8.84', 'learning_rate': '1.686e-05', 'epoch': '0.7242'}
{'loss': '0.6376', 'grad_norm': '2.667', 'learning_rate': '1.675e-05', 'epoch': '0.7393'}
{'loss': '0.6181', 'grad_norm': '5.026', 'learning_rate': '1.664e-05', 'epoch': '0.7544'}
{'loss': '0.6214', 'grad_norm': '5.032', 'learning_rate': '1.653e-05', 'epoch': '0.7695'}
{'loss': '0.6344', 'grad_norm': '2.936', 'learning_rate': '1.641e-05', 'epoch': '0.7846'}
{'loss': '0.6259', 'grad_norm': '2.833', 'learning_rate': '1.63e-05', 'epoch': '0.7996'}
{'loss': '0.6338', 'grad_norm': '2.976', 'learning_rate': '1.619e-05', 'epoch': '0.8147'}
{'loss': '0.6261', 'grad_norm': '3.7', 'learning_rate': '1.608e-05', 'epoch': '0.8298'}
{'loss': '0.6248', 'grad_norm': '3.636', 'learning_rate': '1.597e-05', 'epoch': '0.8449'}
{'loss': '0.6397', 'grad_norm': '3.385', 'learning_rate': '1.586e-05', 'epoch': '0.86'}
{'loss': '0.6462', 'grad_norm': '3.13', 'learning_rate': '1.574e-05', 'epoch': '0.8751'}
{'loss': '0.6319', 'grad_norm': '3.872', 'learning_rate': '1.563e-05', 'epoch': '0.8902'}
{'loss': '0.6293', 'grad_norm': '3.231', 'learning_rate': '1.552e-05', 'epoch': '0.9053'}
{'loss': '0.6192', 'grad_norm': '4.708', 'learning_rate': '1.541e-05', 'epoch': '0.9203'}
{'loss': '0.6174', 'grad_norm': '5.6', 'learning_rate': '1.53e-05', 'epoch': '0.9354'}
{'loss': '0.6468', 'grad_norm': '9.814', 'learning_rate': '1.518e-05', 'epoch': '0.9505'}
{'loss': '0.6454', 'grad_norm': '3.865', 'learning_rate': '1.507e-05', 'epoch': '0.9656'}
{'loss': '0.6116', 'grad_norm': '4.069', 'learning_rate': '1.496e-05', 'epoch': '0.9807'}
{'loss': '0.6437', 'grad_norm': '3.325', 'learning_rate': '1.485e-05', 'epoch': '0.9958'}
 33% 3314/9942 [32:59<1:01:42,  1.79it/s]
  0% 0/1221 [00:00<?, ?it/s]
  0% 2/1221 [00:00<02:06,  9.62it/s]
  0% 3/1221 [00:00<03:00,  6.76it/s]
  0% 4/1221 [00:00<03:28,  5.85it/s]
  0% 5/1221 [00:00<03:45,  5.40it/s]
  0% 6/1221 [00:01<03:53,  5.19it/s]
  1% 7/1221 [00:01<04:01,  5.02it/s]
  1% 8/1221 [00:01<04:04,  4.95it/s]
  1% 9/1221 [00:01<03:59,  5.05it/s]
  1% 10/1221 [00:01<03:56,  5.11it/s]
  1% 11/1221 [00:02<04:05,  4.93it/s]
  1% 12/1221 [00:02<04:07,  4.88it/s]
  1% 13/1221 [00:02<04:08,  4.86it/s]
  1% 14/1221 [00:02<04:01,  5.01it/s]
  1% 15/1221 [00:02<04:04,  4.92it/s]
  1% 16/1221 [00:03<04:13,  4.76it/s]
  1% 17/1221 [00:03<04:13,  4.74it/s]
  1% 18/1221 [00:03<04:13,  4.74it/s]
  2% 19/1221 [00:03<04:11,  4.79it/s]
  2% 20/1221 [00:03<04:03,  4.94it/s]
  2% 21/1221 [00:04<03:59,  5.00it/s]
  2% 22/1221 [00:04<04:02,  4.95it/s]
  2% 23/1221 [00:04<04:06,  4.86it/s]
  2% 24/1221 [00:04<04:08,  4.82it/s]
  2% 25/1221 [00:04<04:07,  4.83it/s]
  2% 26/1221 [00:05<04:07,  4.83it/s]
  2% 27/1221 [00:05<04:06,  4.84it/s]
  2% 28/1221 [00:05<04:07,  4.83it/s]
  2% 29/1221 [00:05<04:10,  4.76it/s]
  2% 30/1221 [00:06<04:10,  4.76it/s]
  3% 31/1221 [00:06<04:15,  4.66it/s]
  3% 32/1221 [00:06<04:16,  4.63it/s]
  3% 33/1221 [00:06<04:13,  4.69it/s]
  3% 34/1221 [00:06<04:12,  4.70it/s]
  3% 35/1221 [00:07<04:10,  4.74it/s]
  3% 36/1221 [00:07<04:07,  4.79it/s]
  3% 37/1221 [00:07<04:13,  4.68it/s]
  3% 38/1221 [00:07<04:15,  4.63it/s]
  3% 39/1221 [00:07<04:03,  4.86it/s]
  3% 40/1221 [00:08<04:07,  4.77it/s]
  3% 41/1221 [00:08<04:10,  4.72it/s]
  3% 42/1221 [00:08<04:14,  4.64it/s]
  4% 43/1221 [00:08<04:11,  4.68it/s]
  4% 44/1221 [00:08<04:14,  4.62it/s]
  4% 45/1221 [00:09<04:17,  4.57it/s]
  4% 46/1221 [00:09<04:07,  4.75it/s]
  4% 47/1221 [00:09<04:06,  4.76it/s]
  4% 48/1221 [00:09<03:59,  4.90it/s]
  4% 49/1221 [00:10<04:01,  4.86it/s]
  4% 50/1221 [00:10<04:03,  4.81it/s]
  4% 51/1221 [00:10<04:00,  4.86it/s]
  4% 52/1221 [00:10<04:01,  4.83it/s]
  4% 53/1221 [00:10<04:01,  4.83it/s]
  4% 54/1221 [00:11<04:07,  4.71it/s]
  5% 55/1221 [00:11<04:07,  4.72it/s]
  5% 56/1221 [00:11<04:05,  4.75it/s]
  5% 57/1221 [00:11<04:03,  4.79it/s]
  5% 58/1221 [00:11<03:54,  4.96it/s]
  5% 59/1221 [00:12<03:56,  4.92it/s]
  5% 60/1221 [00:12<04:00,  4.83it/s]
  5% 61/1221 [00:12<04:09,  4.65it/s]
  5% 62/1221 [00:12<04:06,  4.70it/s]
  5% 63/1221 [00:12<03:59,  4.84it/s]
  5% 64/1221 [00:13<03:59,  4.84it/s]
  5% 65/1221 [00:13<04:00,  4.80it/s]
  5% 66/1221 [00:13<04:05,  4.71it/s]
  5% 67/1221 [00:13<04:08,  4.64it/s]
  6% 68/1221 [00:14<04:08,  4.63it/s]
  6% 69/1221 [00:14<04:06,  4.68it/s]
  6% 70/1221 [00:14<04:10,  4.59it/s]
  6% 71/1221 [00:14<04:01,  4.75it/s]
  6% 72/1221 [00:14<04:01,  4.75it/s]
  6% 73/1221 [00:15<03:54,  4.90it/s]
  6% 74/1221 [00:15<04:03,  4.72it/s]
  6% 75/1221 [00:15<04:02,  4.73it/s]
  6% 76/1221 [00:15<04:07,  4.62it/s]
  6% 77/1221 [00:15<04:10,  4.56it/s]
  6% 78/1221 [00:16<04:05,  4.66it/s]
  6% 79/1221 [00:16<04:02,  4.71it/s]
  7% 80/1221 [00:16<03:50,  4.94it/s]
  7% 81/1221 [00:16<03:57,  4.80it/s]
  7% 82/1221 [00:16<03:50,  4.95it/s]
  7% 83/1221 [00:17<03:56,  4.82it/s]
  7% 84/1221 [00:17<03:56,  4.80it/s]
  7% 85/1221 [00:17<03:53,  4.86it/s]
  7% 86/1221 [00:17<04:00,  4.72it/s]
  7% 87/1221 [00:18<04:05,  4.63it/s]
  7% 88/1221 [00:18<04:04,  4.64it/s]
  7% 89/1221 [00:18<04:00,  4.71it/s]
  7% 90/1221 [00:18<03:50,  4.91it/s]
  7% 91/1221 [00:18<03:46,  4.98it/s]
  8% 92/1221 [00:19<03:57,  4.74it/s]
  8% 93/1221 [00:19<03:57,  4.75it/s]
  8% 94/1221 [00:19<03:57,  4.75it/s]
  8% 95/1221 [00:19<03:55,  4.78it/s]
  8% 96/1221 [00:19<03:52,  4.83it/s]
  8% 97/1221 [00:20<03:56,  4.75it/s]
  8% 98/1221 [00:20<03:57,  4.73it/s]
  8% 99/1221 [00:20<03:57,  4.73it/s]
  8% 100/1221 [00:20<03:48,  4.90it/s]
  8% 101/1221 [00:20<03:43,  5.01it/s]
  8% 102/1221 [00:21<03:48,  4.90it/s]
  8% 103/1221 [00:21<03:56,  4.72it/s]
  9% 104/1221 [00:21<03:48,  4.90it/s]
  9% 105/1221 [00:21<03:43,  4.99it/s]
  9% 106/1221 [00:21<03:37,  5.13it/s]
  9% 107/1221 [00:22<03:42,  5.02it/s]
  9% 108/1221 [00:22<03:45,  4.93it/s]
  9% 109/1221 [00:22<03:48,  4.87it/s]
  9% 110/1221 [00:22<03:47,  4.89it/s]
  9% 111/1221 [00:22<03:41,  5.01it/s]
  9% 112/1221 [00:23<03:45,  4.93it/s]
  9% 113/1221 [00:23<03:39,  5.06it/s]
  9% 114/1221 [00:23<03:43,  4.96it/s]
  9% 115/1221 [00:23<03:45,  4.90it/s]
 10% 116/1221 [00:23<03:43,  4.95it/s]
 10% 117/1221 [00:24<03:46,  4.88it/s]
 10% 118/1221 [00:24<03:52,  4.74it/s]
 10% 119/1221 [00:24<03:53,  4.72it/s]
 10% 120/1221 [00:24<03:44,  4.90it/s]
 10% 121/1221 [00:24<03:39,  5.00it/s]
 10% 122/1221 [00:25<03:44,  4.90it/s]
 10% 123/1221 [00:25<03:52,  4.72it/s]
 10% 124/1221 [00:25<03:45,  4.86it/s]
 10% 125/1221 [00:25<03:46,  4.83it/s]
 10% 126/1221 [00:26<03:45,  4.86it/s]
 10% 127/1221 [00:26<03:47,  4.81it/s]
 10% 128/1221 [00:26<03:45,  4.84it/s]
 11% 129/1221 [00:26<03:46,  4.82it/s]
 11% 130/1221 [00:26<03:45,  4.83it/s]
 11% 131/1221 [00:27<03:39,  4.98it/s]
 11% 132/1221 [00:27<03:35,  5.05it/s]
 11% 133/1221 [00:27<03:38,  4.97it/s]
 11% 134/1221 [00:27<03:42,  4.89it/s]
 11% 135/1221 [00:27<03:40,  4.92it/s]
 11% 136/1221 [00:28<03:42,  4.87it/s]
 11% 137/1221 [00:28<03:50,  4.71it/s]
 11% 138/1221 [00:28<03:48,  4.75it/s]
 11% 139/1221 [00:28<03:49,  4.72it/s]
 11% 140/1221 [00:28<03:47,  4.74it/s]
 12% 141/1221 [00:29<03:40,  4.91it/s]
 12% 142/1221 [00:29<03:40,  4.89it/s]
 12% 143/1221 [00:29<03:40,  4.89it/s]
 12% 144/1221 [00:29<03:44,  4.80it/s]
 12% 145/1221 [00:29<03:47,  4.73it/s]
 12% 146/1221 [00:30<03:50,  4.67it/s]
 12% 147/1221 [00:30<03:41,  4.85it/s]
 12% 148/1221 [00:30<03:45,  4.76it/s]
 12% 149/1221 [00:30<03:38,  4.90it/s]
 12% 150/1221 [00:30<03:45,  4.75it/s]
 12% 151/1221 [00:31<03:44,  4.76it/s]
 12% 152/1221 [00:31<03:44,  4.77it/s]
 13% 153/1221 [00:31<03:47,  4.70it/s]
 13% 154/1221 [00:31<03:50,  4.63it/s]
 13% 155/1221 [00:32<03:39,  4.86it/s]
 13% 156/1221 [00:32<03:40,  4.83it/s]
 13% 157/1221 [00:32<03:46,  4.70it/s]
 13% 158/1221 [00:32<03:38,  4.87it/s]
 13% 159/1221 [00:32<03:34,  4.96it/s]
 13% 160/1221 [00:33<03:28,  5.08it/s]
 13% 161/1221 [00:33<03:27,  5.10it/s]
 13% 162/1221 [00:33<03:26,  5.14it/s]
 13% 163/1221 [00:33<03:23,  5.19it/s]
 13% 164/1221 [00:33<03:30,  5.02it/s]
 14% 165/1221 [00:34<03:32,  4.97it/s]
 14% 166/1221 [00:34<03:28,  5.05it/s]
 14% 167/1221 [00:34<03:33,  4.95it/s]
 14% 168/1221 [00:34<03:41,  4.76it/s]
 14% 169/1221 [00:34<03:34,  4.91it/s]
 14% 170/1221 [00:35<03:38,  4.81it/s]
 14% 171/1221 [00:35<03:38,  4.82it/s]
 14% 172/1221 [00:35<03:38,  4.80it/s]
 14% 173/1221 [00:35<03:36,  4.84it/s]
 14% 174/1221 [00:35<03:39,  4.77it/s]
 14% 175/1221 [00:36<03:40,  4.75it/s]
 14% 176/1221 [00:36<03:33,  4.90it/s]
 14% 177/1221 [00:36<03:33,  4.89it/s]
 15% 178/1221 [00:36<03:28,  5.00it/s]
 15% 179/1221 [00:36<03:30,  4.95it/s]
 15% 180/1221 [00:37<03:36,  4.81it/s]
 15% 181/1221 [00:37<03:31,  4.92it/s]
 15% 182/1221 [00:37<03:34,  4.84it/s]
 15% 183/1221 [00:37<03:28,  4.97it/s]
 15% 184/1221 [00:37<03:29,  4.94it/s]
 15% 185/1221 [00:38<03:37,  4.76it/s]
 15% 186/1221 [00:38<03:41,  4.67it/s]
 15% 187/1221 [00:38<03:35,  4.80it/s]
 15% 188/1221 [00:38<03:29,  4.92it/s]
 15% 189/1221 [00:38<03:30,  4.90it/s]
 16% 190/1221 [00:39<03:38,  4.71it/s]
 16% 191/1221 [00:39<03:31,  4.87it/s]
 16% 192/1221 [00:39<03:33,  4.82it/s]
 16% 193/1221 [00:39<03:38,  4.70it/s]
 16% 194/1221 [00:40<03:37,  4.72it/s]
 16% 195/1221 [00:40<03:41,  4.63it/s]
 16% 196/1221 [00:40<03:40,  4.65it/s]
 16% 197/1221 [00:40<03:35,  4.75it/s]
 16% 198/1221 [00:40<03:34,  4.77it/s]
 16% 199/1221 [00:41<03:32,  4.80it/s]
 16% 200/1221 [00:41<03:40,  4.62it/s]
 16% 201/1221 [00:41<03:39,  4.66it/s]
 17% 202/1221 [00:41<03:35,  4.72it/s]
 17% 203/1221 [00:41<03:34,  4.75it/s]
 17% 204/1221 [00:42<03:33,  4.76it/s]
 17% 205/1221 [00:42<03:34,  4.74it/s]
 17% 206/1221 [00:42<03:34,  4.74it/s]
 17% 207/1221 [00:42<03:30,  4.81it/s]
 17% 208/1221 [00:42<03:28,  4.86it/s]
 17% 209/1221 [00:43<03:28,  4.84it/s]
 17% 210/1221 [00:43<03:24,  4.94it/s]
 17% 211/1221 [00:43<03:26,  4.90it/s]
 17% 212/1221 [00:43<03:26,  4.89it/s]
 17% 213/1221 [00:44<03:28,  4.84it/s]
 18% 214/1221 [00:44<03:23,  4.94it/s]
 18% 215/1221 [00:44<03:30,  4.77it/s]
 18% 216/1221 [00:44<03:30,  4.77it/s]
 18% 217/1221 [00:44<03:33,  4.71it/s]
 18% 218/1221 [00:45<03:33,  4.70it/s]
 18% 219/1221 [00:45<03:38,  4.58it/s]
 18% 220/1221 [00:45<03:42,  4.51it/s]
 18% 221/1221 [00:45<03:36,  4.61it/s]
 18% 222/1221 [00:45<03:38,  4.57it/s]
 18% 223/1221 [00:46<03:34,  4.66it/s]
 18% 224/1221 [00:46<03:32,  4.68it/s]
 18% 225/1221 [00:46<03:24,  4.88it/s]
 19% 226/1221 [00:46<03:18,  5.02it/s]
 19% 227/1221 [00:46<03:23,  4.88it/s]
 19% 228/1221 [00:47<03:18,  5.00it/s]
 19% 229/1221 [00:47<03:20,  4.94it/s]
 19% 230/1221 [00:47<03:23,  4.88it/s]
 19% 231/1221 [00:47<03:23,  4.87it/s]
 19% 232/1221 [00:48<03:25,  4.82it/s]
 19% 233/1221 [00:48<03:23,  4.87it/s]
 19% 234/1221 [00:48<03:18,  4.97it/s]
 19% 235/1221 [00:48<03:16,  5.02it/s]
 19% 236/1221 [00:48<03:12,  5.12it/s]
 19% 237/1221 [00:48<03:11,  5.14it/s]
 19% 238/1221 [00:49<03:15,  5.03it/s]
 20% 239/1221 [00:49<03:19,  4.92it/s]
 20% 240/1221 [00:49<03:21,  4.87it/s]
 20% 241/1221 [00:49<03:27,  4.72it/s]
 20% 242/1221 [00:50<03:31,  4.64it/s]
 20% 243/1221 [00:50<03:34,  4.57it/s]
 20% 244/1221 [00:50<03:31,  4.62it/s]
 20% 245/1221 [00:50<03:30,  4.64it/s]
 20% 246/1221 [00:50<03:28,  4.68it/s]
 20% 247/1221 [00:51<03:29,  4.64it/s]
 20% 248/1221 [00:51<03:22,  4.81it/s]
 20% 249/1221 [00:51<03:26,  4.70it/s]
 20% 250/1221 [00:51<03:29,  4.64it/s]
 21% 251/1221 [00:51<03:25,  4.71it/s]
 21% 252/1221 [00:52<03:20,  4.82it/s]
 21% 253/1221 [00:52<03:20,  4.84it/s]
 21% 254/1221 [00:52<03:26,  4.69it/s]
 21% 255/1221 [00:52<03:23,  4.75it/s]
 21% 256/1221 [00:53<03:22,  4.75it/s]
 21% 257/1221 [00:53<03:24,  4.71it/s]
 21% 258/1221 [00:53<03:18,  4.84it/s]
 21% 259/1221 [00:53<03:23,  4.72it/s]
 21% 260/1221 [00:53<03:17,  4.87it/s]
 21% 261/1221 [00:54<03:22,  4.74it/s]
 21% 262/1221 [00:54<03:21,  4.75it/s]
 22% 263/1221 [00:54<03:15,  4.91it/s]
 22% 264/1221 [00:54<03:16,  4.86it/s]
 22% 265/1221 [00:54<03:17,  4.85it/s]
 22% 266/1221 [00:55<03:13,  4.94it/s]
 22% 267/1221 [00:55<03:16,  4.87it/s]
 22% 268/1221 [00:55<03:16,  4.85it/s]
 22% 269/1221 [00:55<03:11,  4.98it/s]
 22% 270/1221 [00:55<03:12,  4.95it/s]
 22% 271/1221 [00:56<03:13,  4.91it/s]
 22% 272/1221 [00:56<03:17,  4.81it/s]
 22% 273/1221 [00:56<03:18,  4.78it/s]
 22% 274/1221 [00:56<03:17,  4.81it/s]
 23% 275/1221 [00:56<03:15,  4.84it/s]
 23% 276/1221 [00:57<03:21,  4.69it/s]
 23% 277/1221 [00:57<03:21,  4.68it/s]
 23% 278/1221 [00:57<03:20,  4.71it/s]
 23% 279/1221 [00:57<03:20,  4.71it/s]
 23% 280/1221 [00:58<03:23,  4.62it/s]
 23% 281/1221 [00:58<03:26,  4.56it/s]
 23% 282/1221 [00:58<03:23,  4.61it/s]
 23% 283/1221 [00:58<03:20,  4.68it/s]
 23% 284/1221 [00:58<03:19,  4.69it/s]
 23% 285/1221 [00:59<03:17,  4.74it/s]
 23% 286/1221 [00:59<03:17,  4.74it/s]
 24% 287/1221 [00:59<03:21,  4.62it/s]
 24% 288/1221 [00:59<03:18,  4.69it/s]
 24% 289/1221 [00:59<03:10,  4.89it/s]
 24% 290/1221 [01:00<03:12,  4.84it/s]
 24% 291/1221 [01:00<03:12,  4.83it/s]
 24% 292/1221 [01:00<03:12,  4.84it/s]
 24% 293/1221 [01:00<03:13,  4.81it/s]
 24% 294/1221 [01:00<03:12,  4.82it/s]
 24% 295/1221 [01:01<03:12,  4.82it/s]
 24% 296/1221 [01:01<03:10,  4.85it/s]
 24% 297/1221 [01:01<03:11,  4.83it/s]
 24% 298/1221 [01:01<03:11,  4.82it/s]
 24% 299/1221 [01:01<03:12,  4.80it/s]
 25% 300/1221 [01:02<03:17,  4.67it/s]
 25% 301/1221 [01:02<03:15,  4.70it/s]
 25% 302/1221 [01:02<03:19,  4.60it/s]
 25% 303/1221 [01:02<03:15,  4.69it/s]
 25% 304/1221 [01:03<03:13,  4.74it/s]
 25% 305/1221 [01:03<03:15,  4.70it/s]
 25% 306/1221 [01:03<03:07,  4.89it/s]
 25% 307/1221 [01:03<03:13,  4.72it/s]
 25% 308/1221 [01:03<03:12,  4.75it/s]
 25% 309/1221 [01:04<03:14,  4.69it/s]
 25% 310/1221 [01:04<03:13,  4.71it/s]
 25% 311/1221 [01:04<03:12,  4.73it/s]
 26% 312/1221 [01:04<03:18,  4.59it/s]
 26% 313/1221 [01:04<03:14,  4.66it/s]
 26% 314/1221 [01:05<03:06,  4.86it/s]
 26% 315/1221 [01:05<03:06,  4.85it/s]

In [ ]:
!python src/train_roberta.py \
  --model_name roberta-base \
  --data_path data/raw/aita_full.csv \
  --epochs 3 \
  --batch_size 16 \
  --lr 2e-5 \
  --output_dir models/roberta_aita_full_focal_loss

=== Fine-Tuning roberta-base ===
Applying undersampling...
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100% 197/197 [00:00<00:00, 5029.05it/s]
[transformers] RobertaForSequenceClassification LOAD REPORT from: roberta-base
Key                        | Status     |
---------------------------+------------+-
lm_head.bias               | UNEXPECTED |
lm_head.dense.weight       | UNEXPECTED |
lm_head.layer_norm.bias    | UNEXPECTED |
lm_head.dense.bias         | UNEXPECTED |
lm_head.layer_norm.weight  | UNEXPECTED |
classifier.dense.bias      | MISSING    |
classifier.dense.weight    | MISSING    |
classifier.out_proj.weight | MISSING    |
classifier.out_proj.bias   | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
Map: 100% 53020/53020 [00:15<00:00, 3414.07 examples/s]
Map: 100% 19525/19525 [00:05<00:00, 3343.33 examples/s]
[transformers] warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting Fine-Tuning Process...
{'loss': '0.1784', 'grad_norm': '1.508', 'learning_rate': '9.849e-07', 'epoch': '0.01509'}
{'loss': '0.1719', 'grad_norm': '0.7115', 'learning_rate': '1.99e-06', 'epoch': '0.03018'}
{'loss': '0.1686', 'grad_norm': '0.7727', 'learning_rate': '2.995e-06', 'epoch': '0.04526'}
{'loss': '0.1708', 'grad_norm': '0.838', 'learning_rate': '4e-06', 'epoch': '0.06035'}
{'loss': '0.17', 'grad_norm': '1.006', 'learning_rate': '5.005e-06', 'epoch': '0.07544'}
{'loss': '0.1702', 'grad_norm': '0.8751', 'learning_rate': '6.01e-06', 'epoch': '0.09053'}
{'loss': '0.1686', 'grad_norm': '0.5871', 'learning_rate': '7.015e-06', 'epoch': '0.1056'}
{'loss': '0.171', 'grad_norm': '1.819', 'learning_rate': '8.02e-06', 'epoch': '0.1207'}
{'loss': '0.1721', 'grad_norm': '1.054', 'learning_rate': '9.025e-06', 'epoch': '0.1358'}
{'loss': '0.1677', 'grad_norm': '2.388', 'learning_rate': '1.003e-05', 'epoch': '0.1509'}
{'loss': '0.169', 'grad_norm': '1.913', 'learning_rate': '1.104e-05', 'epoch': '0.166'}
{'loss': '0.167', 'grad_norm': '0.7578', 'learning_rate': '1.204e-05', 'epoch': '0.1811'}
{'loss': '0.1686', 'grad_norm': '1.509', 'learning_rate': '1.305e-05', 'epoch': '0.1961'}
{'loss': '0.1676', 'grad_norm': '0.846', 'learning_rate': '1.405e-05', 'epoch': '0.2112'}
{'loss': '0.1724', 'grad_norm': '1.66', 'learning_rate': '1.506e-05', 'epoch': '0.2263'}
{'loss': '0.1689', 'grad_norm': '2.097', 'learning_rate': '1.606e-05', 'epoch': '0.2414'}
{'loss': '0.1706', 'grad_norm': '0.848', 'learning_rate': '1.707e-05', 'epoch': '0.2565'}
{'loss': '0.1654', 'grad_norm': '2.138', 'learning_rate': '1.807e-05', 'epoch': '0.2716'}
{'loss': '0.1675', 'grad_norm': '0.6388', 'learning_rate': '1.908e-05', 'epoch': '0.2867'}
{'loss': '0.1659', 'grad_norm': '1.303', 'learning_rate': '1.999e-05', 'epoch': '0.3018'}
{'loss': '0.1691', 'grad_norm': '1.007', 'learning_rate': '1.988e-05', 'epoch': '0.3168'}
{'loss': '0.1678', 'grad_norm': '0.825', 'learning_rate': '1.977e-05', 'epoch': '0.3319'}
{'loss': '0.1648', 'grad_norm': '2.551', 'learning_rate': '1.966e-05', 'epoch': '0.347'}
{'loss': '0.1647', 'grad_norm': '0.8628', 'learning_rate': '1.954e-05', 'epoch': '0.3621'}
{'loss': '0.1635', 'grad_norm': '0.5426', 'learning_rate': '1.943e-05', 'epoch': '0.3772'}
{'loss': '0.162', 'grad_norm': '2.191', 'learning_rate': '1.932e-05', 'epoch': '0.3923'}
{'loss': '0.1642', 'grad_norm': '0.7809', 'learning_rate': '1.921e-05', 'epoch': '0.4074'}
{'loss': '0.168', 'grad_norm': '3.591', 'learning_rate': '1.91e-05', 'epoch': '0.4225'}
{'loss': '0.1646', 'grad_norm': '0.7689', 'learning_rate': '1.899e-05', 'epoch': '0.4375'}
{'loss': '0.168', 'grad_norm': '0.4862', 'learning_rate': '1.887e-05', 'epoch': '0.4526'}
{'loss': '0.1693', 'grad_norm': '1.602', 'learning_rate': '1.876e-05', 'epoch': '0.4677'}
{'loss': '0.1627', 'grad_norm': '1.713', 'learning_rate': '1.865e-05', 'epoch': '0.4828'}
{'loss': '0.1641', 'grad_norm': '1.054', 'learning_rate': '1.854e-05', 'epoch': '0.4979'}
{'loss': '0.1593', 'grad_norm': '2.524', 'learning_rate': '1.843e-05', 'epoch': '0.513'}
{'loss': '0.1667', 'grad_norm': '0.7588', 'learning_rate': '1.831e-05', 'epoch': '0.5281'}
{'loss': '0.1633', 'grad_norm': '1.727', 'learning_rate': '1.82e-05', 'epoch': '0.5432'}
{'loss': '0.1574', 'grad_norm': '2.173', 'learning_rate': '1.809e-05', 'epoch': '0.5582'}
{'loss': '0.1652', 'grad_norm': '0.6378', 'learning_rate': '1.798e-05', 'epoch': '0.5733'}
{'loss': '0.1595', 'grad_norm': '2.864', 'learning_rate': '1.787e-05', 'epoch': '0.5884'}
{'loss': '0.1681', 'grad_norm': '1.834', 'learning_rate': '1.776e-05', 'epoch': '0.6035'}
{'loss': '0.1636', 'grad_norm': '1.82', 'learning_rate': '1.764e-05', 'epoch': '0.6186'}
{'loss': '0.1669', 'grad_norm': '1.256', 'learning_rate': '1.753e-05', 'epoch': '0.6337'}
{'loss': '0.1631', 'grad_norm': '0.9458', 'learning_rate': '1.742e-05', 'epoch': '0.6488'}
{'loss': '0.1611', 'grad_norm': '1.169', 'learning_rate': '1.731e-05', 'epoch': '0.6639'}
{'loss': '0.1616', 'grad_norm': '1.487', 'learning_rate': '1.72e-05', 'epoch': '0.6789'}
{'loss': '0.1606', 'grad_norm': '2.319', 'learning_rate': '1.709e-05', 'epoch': '0.694'}
{'loss': '0.1596', 'grad_norm': '1.661', 'learning_rate': '1.697e-05', 'epoch': '0.7091'}
{'loss': '0.1632', 'grad_norm': '1.396', 'learning_rate': '1.686e-05', 'epoch': '0.7242'}
{'loss': '0.1609', 'grad_norm': '0.8183', 'learning_rate': '1.675e-05', 'epoch': '0.7393'}
{'loss': '0.1569', 'grad_norm': '1.07', 'learning_rate': '1.664e-05', 'epoch': '0.7544'}
{'loss': '0.1578', 'grad_norm': '1.363', 'learning_rate': '1.653e-05', 'epoch': '0.7695'}
{'loss': '0.162', 'grad_norm': '0.9615', 'learning_rate': '1.641e-05', 'epoch': '0.7846'}
{'loss': '0.1571', 'grad_norm': '0.9941', 'learning_rate': '1.63e-05', 'epoch': '0.7996'}
{'loss': '0.1619', 'grad_norm': '0.8685', 'learning_rate': '1.619e-05', 'epoch': '0.8147'}
{'loss': '0.158', 'grad_norm': '1.758', 'learning_rate': '1.608e-05', 'epoch': '0.8298'}
{'loss': '0.1604', 'grad_norm': '1.051', 'learning_rate': '1.597e-05', 'epoch': '0.8449'}
{'loss': '0.1626', 'grad_norm': '1.233', 'learning_rate': '1.586e-05', 'epoch': '0.86'}
{'loss': '0.1636', 'grad_norm': '0.8778', 'learning_rate': '1.574e-05', 'epoch': '0.8751'}
{'loss': '0.1603', 'grad_norm': '1.067', 'learning_rate': '1.563e-05', 'epoch': '0.8902'}
{'loss': '0.1599', 'grad_norm': '0.8412', 'learning_rate': '1.552e-05', 'epoch': '0.9053'}
{'loss': '0.1592', 'grad_norm': '1.149', 'learning_rate': '1.541e-05', 'epoch': '0.9203'}
{'loss': '0.1562', 'grad_norm': '1.339', 'learning_rate': '1.53e-05', 'epoch': '0.9354'}
{'loss': '0.1622', 'grad_norm': '1.67', 'learning_rate': '1.518e-05', 'epoch': '0.9505'}
{'loss': '0.1627', 'grad_norm': '0.7933', 'learning_rate': '1.507e-05', 'epoch': '0.9656'}
{'loss': '0.1564', 'grad_norm': '1.843', 'learning_rate': '1.496e-05', 'epoch': '0.9807'}
{'loss': '0.1635', 'grad_norm': '0.9792', 'learning_rate': '1.485e-05', 'epoch': '0.9958'}
 33% 3314/9942 [33:00<1:01:24,  1.80it/s]
  0% 0/1221 [00:00<?, ?it/s]
  0% 2/1221 [00:00<02:05,  9.72it/s]
  0% 3/1221 [00:00<02:58,  6.81it/s]
  0% 4/1221 [00:00<03:28,  5.84it/s]
  0% 5/1221 [00:00<03:43,  5.43it/s]
  0% 6/1221 [00:01<03:53,  5.20it/s]
  1% 7/1221 [00:01<03:59,  5.06it/s]
  1% 8/1221 [00:01<04:05,  4.93it/s]
  1% 9/1221 [00:01<04:00,  5.05it/s]
  1% 10/1221 [00:01<03:56,  5.11it/s]
  1% 11/1221 [00:02<04:05,  4.94it/s]
  1% 12/1221 [00:02<04:06,  4.91it/s]
  1% 13/1221 [00:02<04:09,  4.84it/s]
  1% 14/1221 [00:02<04:01,  4.99it/s]
  1% 15/1221 [00:02<04:04,  4.94it/s]
  1% 16/1221 [00:03<04:12,  4.77it/s]
  1% 17/1221 [00:03<04:12,  4.77it/s]
  1% 18/1221 [00:03<04:14,  4.73it/s]
  2% 19/1221 [00:03<04:11,  4.78it/s]
  2% 20/1221 [00:03<04:04,  4.92it/s]
  2% 21/1221 [00:04<03:58,  5.02it/s]
  2% 22/1221 [00:04<04:02,  4.95it/s]
  2% 23/1221 [00:04<04:05,  4.89it/s]
  2% 24/1221 [00:04<04:07,  4.84it/s]
  2% 25/1221 [00:04<04:06,  4.84it/s]
  2% 26/1221 [00:05<04:05,  4.87it/s]
  2% 27/1221 [00:05<04:07,  4.83it/s]
  2% 28/1221 [00:05<04:06,  4.83it/s]
  2% 29/1221 [00:05<04:11,  4.74it/s]
  2% 30/1221 [00:05<04:11,  4.74it/s]
  3% 31/1221 [00:06<04:16,  4.64it/s]
  3% 32/1221 [00:06<04:16,  4.64it/s]
  3% 33/1221 [00:06<04:14,  4.68it/s]
  3% 34/1221 [00:06<04:14,  4.66it/s]
  3% 35/1221 [00:07<04:11,  4.71it/s]
  3% 36/1221 [00:07<04:08,  4.77it/s]
  3% 37/1221 [00:07<04:12,  4.69it/s]
  3% 38/1221 [00:07<04:15,  4.62it/s]
  3% 39/1221 [00:07<04:04,  4.84it/s]
  3% 40/1221 [00:08<04:07,  4.77it/s]
  3% 41/1221 [00:08<04:08,  4.74it/s]
  3% 42/1221 [00:08<04:13,  4.65it/s]
  4% 43/1221 [00:08<04:10,  4.71it/s]
  4% 44/1221 [00:08<04:15,  4.62it/s]
  4% 45/1221 [00:09<04:18,  4.56it/s]
  4% 46/1221 [00:09<04:07,  4.75it/s]
  4% 47/1221 [00:09<04:06,  4.76it/s]
  4% 48/1221 [00:09<03:59,  4.90it/s]
  4% 49/1221 [00:10<04:01,  4.86it/s]
  4% 50/1221 [00:10<04:01,  4.84it/s]
  4% 51/1221 [00:10<03:59,  4.88it/s]
  4% 52/1221 [00:10<04:01,  4.84it/s]
  4% 53/1221 [00:10<04:01,  4.83it/s]
  4% 54/1221 [00:11<04:09,  4.68it/s]
  5% 55/1221 [00:11<04:07,  4.71it/s]
  5% 56/1221 [00:11<04:05,  4.74it/s]
  5% 57/1221 [00:11<04:04,  4.76it/s]
  5% 58/1221 [00:11<03:55,  4.94it/s]
  5% 59/1221 [00:12<03:57,  4.89it/s]
  5% 60/1221 [00:12<04:00,  4.83it/s]
  5% 61/1221 [00:12<04:09,  4.66it/s]
  5% 62/1221 [00:12<04:05,  4.71it/s]
  5% 63/1221 [00:12<03:59,  4.84it/s]
  5% 64/1221 [00:13<03:58,  4.85it/s]
  5% 65/1221 [00:13<04:00,  4.81it/s]
  5% 66/1221 [00:13<04:04,  4.71it/s]
  5% 67/1221 [00:13<04:09,  4.63it/s]
  6% 68/1221 [00:14<04:08,  4.64it/s]
  6% 69/1221 [00:14<04:05,  4.69it/s]
  6% 70/1221 [00:14<04:10,  4.60it/s]
  6% 71/1221 [00:14<04:01,  4.77it/s]
  6% 72/1221 [00:14<04:02,  4.74it/s]
  6% 73/1221 [00:15<03:53,  4.91it/s]
  6% 74/1221 [00:15<04:02,  4.72it/s]
  6% 75/1221 [00:15<04:02,  4.73it/s]
  6% 76/1221 [00:15<04:07,  4.63it/s]
  6% 77/1221 [00:15<04:10,  4.56it/s]
  6% 78/1221 [00:16<04:04,  4.68it/s]
  6% 79/1221 [00:16<04:02,  4.71it/s]
  7% 80/1221 [00:16<03:51,  4.92it/s]
  7% 81/1221 [00:16<03:58,  4.78it/s]
  7% 82/1221 [00:16<03:50,  4.94it/s]
  7% 83/1221 [00:17<03:56,  4.81it/s]
  7% 84/1221 [00:17<03:57,  4.79it/s]
  7% 85/1221 [00:17<03:53,  4.86it/s]
  7% 86/1221 [00:17<04:00,  4.71it/s]
  7% 87/1221 [00:18<04:04,  4.64it/s]
  7% 88/1221 [00:18<04:03,  4.66it/s]
  7% 89/1221 [00:18<03:59,  4.73it/s]
  7% 90/1221 [00:18<03:48,  4.94it/s]
  7% 91/1221 [00:18<03:46,  4.98it/s]
  8% 92/1221 [00:19<03:54,  4.82it/s]
  8% 93/1221 [00:19<03:53,  4.82it/s]
  8% 94/1221 [00:19<03:55,  4.79it/s]
  8% 95/1221 [00:19<03:55,  4.77it/s]
  8% 96/1221 [00:19<03:53,  4.82it/s]
  8% 97/1221 [00:20<03:56,  4.75it/s]
  8% 98/1221 [00:20<03:54,  4.79it/s]
  8% 99/1221 [00:20<03:54,  4.79it/s]
  8% 100/1221 [00:20<03:47,  4.93it/s]
  8% 101/1221 [00:20<03:42,  5.03it/s]
  8% 102/1221 [00:21<03:46,  4.93it/s]
  8% 103/1221 [00:21<03:54,  4.78it/s]
  9% 104/1221 [00:21<03:46,  4.94it/s]
  9% 105/1221 [00:21<03:43,  5.00it/s]
  9% 106/1221 [00:21<03:38,  5.11it/s]
  9% 107/1221 [00:22<03:43,  4.98it/s]
  9% 108/1221 [00:22<03:45,  4.93it/s]
  9% 109/1221 [00:22<03:47,  4.88it/s]
  9% 110/1221 [00:22<03:48,  4.87it/s]
  9% 111/1221 [00:22<03:42,  4.99it/s]
  9% 112/1221 [00:23<03:45,  4.91it/s]
  9% 113/1221 [00:23<03:39,  5.04it/s]
  9% 114/1221 [00:23<03:42,  4.97it/s]
  9% 115/1221 [00:23<03:45,  4.90it/s]
 10% 116/1221 [00:23<03:44,  4.92it/s]
 10% 117/1221 [00:24<03:47,  4.86it/s]
 10% 118/1221 [00:24<03:52,  4.74it/s]
 10% 119/1221 [00:24<03:52,  4.74it/s]
 10% 120/1221 [00:24<03:44,  4.91it/s]
 10% 121/1221 [00:24<03:40,  4.99it/s]
 10% 122/1221 [00:25<03:45,  4.88it/s]
 10% 123/1221 [00:25<03:49,  4.78it/s]
 10% 124/1221 [00:25<03:42,  4.93it/s]
 10% 125/1221 [00:25<03:44,  4.89it/s]
 10% 126/1221 [00:25<03:44,  4.87it/s]
 10% 127/1221 [00:26<03:47,  4.80it/s]
 10% 128/1221 [00:26<03:45,  4.85it/s]
 11% 129/1221 [00:26<03:46,  4.82it/s]
 11% 130/1221 [00:26<03:45,  4.84it/s]
 11% 131/1221 [00:27<03:40,  4.95it/s]
 11% 132/1221 [00:27<03:36,  5.03it/s]
 11% 133/1221 [00:27<03:38,  4.98it/s]
 11% 134/1221 [00:27<03:40,  4.92it/s]
 11% 135/1221 [00:27<03:39,  4.94it/s]
 11% 136/1221 [00:28<03:43,  4.86it/s]
 11% 137/1221 [00:28<03:49,  4.71it/s]
 11% 138/1221 [00:28<03:47,  4.76it/s]
 11% 139/1221 [00:28<03:47,  4.75it/s]
 11% 140/1221 [00:28<03:46,  4.77it/s]
 12% 141/1221 [00:29<03:38,  4.94it/s]
 12% 142/1221 [00:29<03:39,  4.91it/s]
 12% 143/1221 [00:29<03:38,  4.93it/s]
 12% 144/1221 [00:29<03:42,  4.85it/s]
 12% 145/1221 [00:29<03:46,  4.76it/s]
 12% 146/1221 [00:30<03:50,  4.66it/s]
 12% 147/1221 [00:30<03:42,  4.83it/s]
 12% 148/1221 [00:30<03:44,  4.78it/s]
 12% 149/1221 [00:30<03:37,  4.94it/s]
 12% 150/1221 [00:30<03:45,  4.75it/s]
 12% 151/1221 [00:31<03:44,  4.76it/s]
 12% 152/1221 [00:31<03:44,  4.76it/s]
 13% 153/1221 [00:31<03:45,  4.74it/s]
 13% 154/1221 [00:31<03:49,  4.65it/s]
 13% 155/1221 [00:31<03:38,  4.88it/s]
 13% 156/1221 [00:32<03:39,  4.85it/s]
 13% 157/1221 [00:32<03:46,  4.70it/s]
 13% 158/1221 [00:32<03:36,  4.91it/s]
 13% 159/1221 [00:32<03:32,  5.00it/s]
 13% 160/1221 [00:32<03:28,  5.09it/s]
 13% 161/1221 [00:33<03:27,  5.12it/s]
 13% 162/1221 [00:33<03:25,  5.16it/s]
 13% 163/1221 [00:33<03:22,  5.22it/s]
 13% 164/1221 [00:33<03:28,  5.06it/s]
 14% 165/1221 [00:33<03:32,  4.97it/s]
 14% 166/1221 [00:34<03:29,  5.04it/s]
 14% 167/1221 [00:34<03:33,  4.95it/s]
 14% 168/1221 [00:34<03:39,  4.81it/s]
 14% 169/1221 [00:34<03:32,  4.96it/s]
 14% 170/1221 [00:35<03:37,  4.84it/s]
 14% 171/1221 [00:35<03:36,  4.84it/s]
 14% 172/1221 [00:35<03:37,  4.83it/s]
 14% 173/1221 [00:35<03:35,  4.87it/s]
 14% 174/1221 [00:35<03:37,  4.81it/s]
 14% 175/1221 [00:36<03:40,  4.75it/s]
 14% 176/1221 [00:36<03:33,  4.89it/s]
 14% 177/1221 [00:36<03:33,  4.90it/s]
 15% 178/1221 [00:36<03:27,  5.03it/s]
 15% 179/1221 [00:36<03:30,  4.95it/s]
 15% 180/1221 [00:37<03:37,  4.78it/s]
 15% 181/1221 [00:37<03:31,  4.92it/s]
 15% 182/1221 [00:37<03:33,  4.87it/s]
 15% 183/1221 [00:37<03:27,  5.01it/s]
 15% 184/1221 [00:37<03:29,  4.96it/s]
 15% 185/1221 [00:38<03:37,  4.77it/s]
 15% 186/1221 [00:38<03:41,  4.67it/s]
 15% 187/1221 [00:38<03:34,  4.82it/s]
 15% 188/1221 [00:38<03:29,  4.93it/s]
 15% 189/1221 [00:38<03:30,  4.90it/s]
 16% 190/1221 [00:39<03:37,  4.74it/s]
 16% 191/1221 [00:39<03:31,  4.88it/s]
 16% 192/1221 [00:39<03:32,  4.83it/s]
 16% 193/1221 [00:39<03:39,  4.69it/s]
 16% 194/1221 [00:39<03:37,  4.73it/s]
 16% 195/1221 [00:40<03:41,  4.63it/s]
 16% 196/1221 [00:40<03:39,  4.68it/s]
 16% 197/1221 [00:40<03:34,  4.77it/s]
 16% 198/1221 [00:40<03:34,  4.78it/s]
 16% 199/1221 [00:41<03:32,  4.81it/s]
 16% 200/1221 [00:41<03:38,  4.68it/s]
 16% 201/1221 [00:41<03:35,  4.74it/s]
 17% 202/1221 [00:41<03:34,  4.75it/s]
 17% 203/1221 [00:41<03:33,  4.77it/s]
 17% 204/1221 [00:42<03:32,  4.78it/s]
 17% 205/1221 [00:42<03:32,  4.77it/s]
 17% 206/1221 [00:42<03:31,  4.80it/s]
 17% 207/1221 [00:42<03:30,  4.82it/s]
 17% 208/1221 [00:42<03:28,  4.86it/s]
 17% 209/1221 [00:43<03:28,  4.84it/s]
 17% 210/1221 [00:43<03:22,  4.98it/s]
 17% 211/1221 [00:43<03:23,  4.96it/s]
 17% 212/1221 [00:43<03:24,  4.92it/s]
 17% 213/1221 [00:43<03:26,  4.88it/s]
 18% 214/1221 [00:44<03:21,  4.99it/s]
 18% 215/1221 [00:44<03:28,  4.82it/s]
 18% 216/1221 [00:44<03:28,  4.82it/s]
 18% 217/1221 [00:44<03:33,  4.71it/s]
 18% 218/1221 [00:44<03:32,  4.72it/s]
 18% 219/1221 [00:45<03:36,  4.62it/s]
 18% 220/1221 [00:45<03:39,  4.55it/s]
 18% 221/1221 [00:45<03:36,  4.63it/s]
 18% 222/1221 [00:45<03:39,  4.55it/s]
 18% 223/1221 [00:46<03:34,  4.65it/s]
 18% 224/1221 [00:46<03:31,  4.71it/s]
 18% 225/1221 [00:46<03:23,  4.88it/s]
 19% 226/1221 [00:46<03:18,  5.02it/s]
 19% 227/1221 [00:46<03:24,  4.85it/s]
 19% 228/1221 [00:47<03:18,  5.01it/s]
 19% 229/1221 [00:47<03:19,  4.96it/s]
 19% 230/1221 [00:47<03:22,  4.90it/s]
 19% 231/1221 [00:47<03:22,  4.88it/s]
 19% 232/1221 [00:47<03:25,  4.82it/s]
 19% 233/1221 [00:48<03:22,  4.89it/s]
 19% 234/1221 [00:48<03:15,  5.04it/s]
 19% 235/1221 [00:48<03:14,  5.08it/s]
 19% 236/1221 [00:48<03:11,  5.16it/s]
 19% 237/1221 [00:48<03:10,  5.16it/s]
 19% 238/1221 [00:49<03:14,  5.05it/s]
 20% 239/1221 [00:49<03:18,  4.95it/s]
 20% 240/1221 [00:49<03:20,  4.90it/s]
 20% 241/1221 [00:49<03:26,  4.74it/s]
 20% 242/1221 [00:49<03:30,  4.66it/s]
 20% 243/1221 [00:50<03:33,  4.57it/s]
 20% 244/1221 [00:50<03:32,  4.60it/s]
 20% 245/1221 [00:50<03:31,  4.62it/s]
 20% 246/1221 [00:50<03:27,  4.69it/s]
 20% 247/1221 [00:50<03:27,  4.70it/s]
 20% 248/1221 [00:51<03:21,  4.84it/s]
 20% 249/1221 [00:51<03:27,  4.68it/s]
 20% 250/1221 [00:51<03:29,  4.62it/s]
 21% 251/1221 [00:51<03:25,  4.72it/s]
 21% 252/1221 [00:52<03:19,  4.85it/s]
 21% 253/1221 [00:52<03:20,  4.82it/s]
 21% 254/1221 [00:52<03:26,  4.68it/s]
 21% 255/1221 [00:52<03:24,  4.73it/s]
 21% 256/1221 [00:52<03:21,  4.80it/s]
 21% 257/1221 [00:53<03:21,  4.78it/s]
 21% 258/1221 [00:53<03:17,  4.88it/s]
 21% 259/1221 [00:53<03:24,  4.71it/s]
 21% 260/1221 [00:53<03:17,  4.87it/s]
 21% 261/1221 [00:53<03:21,  4.77it/s]
 21% 262/1221 [00:54<03:20,  4.78it/s]
 22% 263/1221 [00:54<03:14,  4.92it/s]
 22% 264/1221 [00:54<03:17,  4.85it/s]
 22% 265/1221 [00:54<03:18,  4.83it/s]
 22% 266/1221 [00:54<03:13,  4.93it/s]
 22% 267/1221 [00:55<03:15,  4.88it/s]
 22% 268/1221 [00:55<03:16,  4.86it/s]
 22% 269/1221 [00:55<03:10,  5.01it/s]
 22% 270/1221 [00:55<03:11,  4.96it/s]
 22% 271/1221 [00:55<03:13,  4.91it/s]
 22% 272/1221 [00:56<03:15,  4.84it/s]
 22% 273/1221 [00:56<03:17,  4.80it/s]
 22% 274/1221 [00:56<03:15,  4.85it/s]
 23% 275/1221 [00:56<03:14,  4.86it/s]
 23% 276/1221 [00:57<03:20,  4.72it/s]
 23% 277/1221 [00:57<03:20,  4.70it/s]
 23% 278/1221 [00:57<03:19,  4.73it/s]
 23% 279/1221 [00:57<03:18,  4.75it/s]
 23% 280/1221 [00:57<03:22,  4.64it/s]
 23% 281/1221 [00:58<03:26,  4.56it/s]
 23% 282/1221 [00:58<03:22,  4.63it/s]
 23% 283/1221 [00:58<03:20,  4.69it/s]
 23% 284/1221 [00:58<03:18,  4.72it/s]
 23% 285/1221 [00:58<03:16,  4.76it/s]
 23% 286/1221 [00:59<03:16,  4.75it/s]
 24% 287/1221 [00:59<03:20,  4.66it/s]
 24% 288/1221 [00:59<03:19,  4.68it/s]
 24% 289/1221 [00:59<03:10,  4.90it/s]
 24% 290/1221 [00:59<03:12,  4.85it/s]
 24% 291/1221 [01:00<03:13,  4.81it/s]
 24% 292/1221 [01:00<03:11,  4.85it/s]
 24% 293/1221 [01:00<03:12,  4.83it/s]
 24% 294/1221 [01:00<03:12,  4.83it/s]
 24% 295/1221 [01:01<03:12,  4.82it/s]
 24% 296/1221 [01:01<03:11,  4.83it/s]
 24% 297/1221 [01:01<03:11,  4.82it/s]
 24% 298/1221 [01:01<03:11,  4.82it/s]
 24% 299/1221 [01:01<03:11,  4.81it/s]
 25% 300/1221 [01:02<03:16,  4.70it/s]
 25% 301/1221 [01:02<03:14,  4.73it/s]
 25% 302/1221 [01:02<03:18,  4.63it/s]
 25% 303/1221 [01:02<03:14,  4.71it/s]
 25% 304/1221 [01:02<03:13,  4.74it/s]
 25% 305/1221 [01:03<03:14,  4.71it/s]
 25% 306/1221 [01:03<03:06,  4.90it/s]
 25% 307/1221 [01:03<03:13,  4.72it/s]
 25% 308/1221 [01:03<03:13,  4.73it/s]
 25% 309/1221 [01:03<03:15,  4.66it/s]
 25% 310/1221 [01:04<03:14,  4.69it/s]
 25% 311/1221 [01:04<03:12,  4.73it/s]
 26% 312/1221 [01:04<03:16,  4.63it/s]
 26% 313/1221 [01:04<03:13,  4.68it/s]
 26% 314/1221 [01:05<03:06,  4.87it/s]
 26% 315/1221 [01:05<03:07,  4.84it/s]
 26% 316/1221 [01:05<03:09,  4.77it/s]
 26% 317/1221 [01:05<03:11,  4.72it/s]
 26% 318/1221 [01:05<03:08,  4.79it/s]
 26% 319/1221 [01:06<03:06,  4.83it/s]
 26% 320/1221 [01:06<03:07,  4.81it/s]
 26% 321/1221 [01:06<03:11,  4.69it/s]
 26% 322/1221 [01:06<03:05,  4.84it/s]
 26% 323/1221 [01:06<03:06,  4.82it/s]
 27% 324/1221 [01:07<03:09,  4.74it/s]
 27% 325/1221 [01:07<03:01,  4.93it/s]
 27% 326/1221 [01:07<03:02,  4.91it/s]
 27% 327/1221 [01:07<03:03,  4.88it/s]
 27% 328/1221 [01:07<03:04,  4.85it/s]
 27% 329/1221 [01:08<03:00,  4.94it/s]

In [ ]:
!zip -r roberta_aita_full_focal_loss.zip models/roberta_aita_full_focal_loss

  adding: models/roberta_aita_full_focal_loss/ (stored 0%)
  adding: models/roberta_aita_full_focal_loss/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full_focal_loss/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/ (stored 0%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/trainer_state.json (deflated 75%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/rng_state.pth (deflated 26%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/optimizer.pt (deflated 16%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/config.json (deflated 50%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/tokenizer.json (deflated 82%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-6628/scheduler.pt (deflated 61%)
  adding: models/roberta_aita_full_focal_loss/config.json (deflated 50%)
  adding: models/roberta_aita_full_focal_loss/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/ (stored 0%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/trainer_state.json (deflated 74%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/rng_state.pth (deflated 26%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/optimizer.pt (deflated 16%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/config.json (deflated 50%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/tokenizer.json (deflated 82%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-3314/scheduler.pt (deflated 61%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/ (stored 0%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/trainer_state.json (deflated 75%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/rng_state.pth (deflated 26%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/optimizer.pt (deflated 16%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/config.json (deflated 50%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/tokenizer.json (deflated 82%)
  adding: models/roberta_aita_full_focal_loss/checkpoint-9942/scheduler.pt (deflated 61%)
  adding: models/roberta_aita_full_focal_loss/tokenizer.json (deflated 82%)

In [ ]:
!zip -r roberta_aita_full.zip models/roberta_aita_full

  adding: models/roberta_aita_full/ (stored 0%)
  adding: models/roberta_aita_full/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full/checkpoint-6628/ (stored 0%)
  adding: models/roberta_aita_full/checkpoint-6628/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full/checkpoint-6628/trainer_state.json (deflated 75%)
  adding: models/roberta_aita_full/checkpoint-6628/rng_state.pth (deflated 26%)
  adding: models/roberta_aita_full/checkpoint-6628/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full/checkpoint-6628/optimizer.pt (deflated 16%)
  adding: models/roberta_aita_full/checkpoint-6628/config.json (deflated 51%)
  adding: models/roberta_aita_full/checkpoint-6628/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full/checkpoint-6628/tokenizer.json (deflated 82%)
  adding: models/roberta_aita_full/checkpoint-6628/scheduler.pt (deflated 61%)
  adding: models/roberta_aita_full/config.json (deflated 51%)
  adding: models/roberta_aita_full/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full/checkpoint-3314/ (stored 0%)
  adding: models/roberta_aita_full/checkpoint-3314/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full/checkpoint-3314/trainer_state.json (deflated 74%)
  adding: models/roberta_aita_full/checkpoint-3314/rng_state.pth (deflated 26%)
  adding: models/roberta_aita_full/checkpoint-3314/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full/checkpoint-3314/optimizer.pt (deflated 16%)
  adding: models/roberta_aita_full/checkpoint-3314/config.json (deflated 51%)
  adding: models/roberta_aita_full/checkpoint-3314/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full/checkpoint-3314/tokenizer.json (deflated 82%)
  adding: models/roberta_aita_full/checkpoint-3314/scheduler.pt (deflated 61%)
  adding: models/roberta_aita_full/checkpoint-9942/ (stored 0%)
  adding: models/roberta_aita_full/checkpoint-9942/tokenizer_config.json (deflated 51%)
  adding: models/roberta_aita_full/checkpoint-9942/trainer_state.json (deflated 76%)
  adding: models/roberta_aita_full/checkpoint-9942/rng_state.pth (deflated 26%)
  adding: models/roberta_aita_full/checkpoint-9942/training_args.bin (deflated 53%)
  adding: models/roberta_aita_full/checkpoint-9942/optimizer.pt (deflated 16%)
  adding: models/roberta_aita_full/checkpoint-9942/config.json (deflated 51%)
  adding: models/roberta_aita_full/checkpoint-9942/model.safetensors (deflated 8%)
  adding: models/roberta_aita_full/checkpoint-9942/tokenizer.json (deflated 82%)
  adding: models/roberta_aita_full/checkpoint-9942/scheduler.pt (deflated 61%)
  adding: models/roberta_aita_full/tokenizer.json (deflated 82%)

In [ ]:
from google.colab import files
files.download('roberta_aita_full_focal_loss.zip')

FileNotFoundError: Cannot find file: roberta_aita_full_focal_loss.zip